miragejs/ember-cli-mirage

blueprints/ember-pretenderify/index.js
Current version is [`1.3.1`](https://github.com/fivetanley/ember-inflector-bower/blob/master/bower.json#L3)
=> Updates `ember-inflector` version

blueprints/ember-pretenderify/index.js
Reverts samselikoff/ember-pretenderify#14
=> Revert "Updates `ember-inflector` version"

blueprints/ember-pretenderify/index.js
Reverts samselikoff/ember-pretenderify#15
=> Revert "Revert "Updates `ember-inflector` version""

addon/server.js
making attributes overridable on server's *createList* method
=> overrides on createList server method

tests/unit/server-test.js
Showing some  :heart:  :heart:  for this awesome project
=> Add createList tests

blueprints/.jshintrc, blueprints/factory/files/app/mirage/factories/__name__.js, blueprints/factory/index.js, blueprints/fixture/files/app/mirage/fixtures/__name__.js, blueprints/fixture/index.js
This PR adds blueprints for mirage-factory and mirage-fixture as described in #51
I don't have any tests for them yet, would you like me to add the blueprint testing helpers so they can be tested?
=> [FEATURE] Add mirage-factory and mirage-fixture blueprints

addon/controllers/front.js
=> Determine status code in constant linear time

config/ember-try.js, package.json
Adds ember try addon and includes a configuration to test against the current version of ember, the beta release and ember canary.
Related issues:
https://github.com/samselikoff/ember-cli-mirage/issues/73
=> Adds ember-try addon and configuration.

package.json
=> Put broccoli-merge-trees and broccoli-funnel as dependencies

.jshintrc, Brocfile.js, addon/factory.js, bower.json, tests/unit/server-test.js
=> [WIP] Added lodash extend function to use instead of jquery.extend

README.md
* include `assert` as a `test` callback parameter
* use ES2015 fat arrow syntax where applicable
=> Update README example syntax

docs/latest/routes.md
It took me a minute to realize why I was getting "ReferenceError: Mirage is not defined". Maybe this will help the next person.
=> make it obvious to import Mirage when using new Mirage.Response

addon/faker.js, blueprints/ember-cli-mirage/index.js, bower.json
=> Update to Faker 3.0.0.

addon/faker.js
=> Expose all of faker via shim.

bower.json, ember-cli-build.js, package.json, testem.json
=> Update to ember-cli 1.13.1

blueprints/ember-cli-mirage/index.js, bower.json, index.js, package.json, tests/unit/import-files-test-node.js
Upgrade to the latest inflector to be compatible with Ember 2.0.0. This fixes #221
=> Remove ember-inflector bower dependency and add the NPM version

addon/server.js
=> Improve missing route error message.

package.json
Upstream: https://github.com/stefanpenner/ember-inflector/pull/89
=> Fixed fatal regex error in older Firefox and IE8

docs/v0.1.x/server-configuration.md
=> [DOCS] Fix typo

addon/faker.js, tests/unit/faker-test.js
Created new PR for this functionality with a single commit
=> Generated function to generate a random number in a range

addon/db-collection.js
A common "parse, and then stringify" pattern was repeated everywhere.
This commit extracts this pattern into a helper function.
=> Refactor Stringifying in DB-Collection

blueprints/ember-cli-mirage/files/__root__/mirage/config.js
=> Fix syntax error in blueprint's example code

docs/v0.1.x/shorthands.md
Hey there,
I *think* there is a typo in the current documentation :)
=> Fix PUT shorthand doc

addon/route-handlers/shorthands/base.js, addon/serializer-registry.js, addon/serializers/active-model-serializer.js, addon/serializers/json-api-serializer.js, addon/utils/inflector.js, tests/integration/serializers/json-api-serializer/associations/collection-test.js, tests/integration/serializers/json-api-serializer/associations/model-test.js, tests/integration/serializers/json-api-serializer/assorted-collections-test.js, tests/integration/serializers/json-api-serializer/attribute-key-formatting-test.js, tests/integration/serializers/json-api-serializer/attrs-test.js, tests/integration/serializers/json-api-serializer/base-test.js, tests/unit/serializers/active-model-serializer-test.js
- Also add tests for AMS serializer #normalize
=> JsonApiSerializer

README.md
=> The old link was broken

addon/db-collection.js, tests/integration/schema/read-test.js, tests/unit/db-test.js
Querying can now be done with a function in case you want to do super
spicy things with Mirage! Peep this example:
let legalDrinkersInCanada = db.users.where(function(user) {
return user.age > 19;
});
Boom! Resolves #365
=> DB Supports Querying with a Filter Function

docs/v0.1.x/shorthands.md, docs/v0.2.x/shorthands.md
ping @samselikoff - per my local PR for this change.
=> Change `put` to `del` in expanded shorthands

addon/route-handler.js, tests/integration/server/shorthand-sanity-test.js
=> fixes bug when `delete` default handler was returning 200

package.json
=> updated dependencies 

CHANGELOG.md, addon/db-collection.js, tests/integration/schema/belongs-to/belongs-to-helper.js, tests/integration/schema/has-many/has-many-helper.js, tests/integration/serializers/json-api-serializer/associations/model-test.js, tests/unit/db-test.js
=> Improve ID Auto-Incrementation

addon/route-handlers/shorthands/base.js, tests/unit/route-handlers/shorthands/base-test.js
=> fixes issue with trailing slash

addon/server.js
fixes #391
`server.create()` is triggering `this.db[collection]` for every record and creates a copy of the collection. This causes a huge performance regression when creating a lot of factories. In this PR we trigger `this.db[collection]` also in `server.createList()` and pass it as an argument in `server.create()`.
=> Fixes performance regression for createList

addon/server.js, tests/unit/server-test.js
This PR would provide https://github.com/samselikoff/ember-cli-mirage/issues/456
=> expose build and buildList methods on Server

addon/index.js
fixes #465 
Do we need tests that check for existence of these named exports?
=> adds exports for ActiveModel and JSONAPI serializer to index

addon/server.js
it would be easier to read/manage code if creating pretender logic is outside class
=> server class cleanup

tests/acceptance/pets-test.js, tests/dummy/app/router.js, tests/dummy/app/routes/application.js, tests/dummy/app/routes/close-friends.js, tests/dummy/app/routes/friends.js, tests/dummy/app/routes/pets.js, tests/dummy/app/templates/edit.hbs, tests/dummy/app/templates/pets.hbs, tests/dummy/mirage/scenarios/default.js
I saw there are some pets object being created in dummy app but they were missing route and tests, aded simple route and tests
=> added dummy pets route

addon/assert.js, addon/route-handler.js, addon/route-handlers/shorthands/base.js, addon/route-handlers/shorthands/delete.js, addon/route-handlers/shorthands/get.js, addon/route-handlers/shorthands/post.js, addon/route-handlers/shorthands/put.js, addon/server.js
=> added assert function

addon/server.js
=> added individual route timing option

addon/orm/schema.js, tests/integration/schema/read-test.js
Hi. trying to solve #501. This is my 1st contribution, so please go easy on me. Let me know if needs any modification.
=> Adds ModelClass.first()

addon/orm/associations/has-many.js, tests/integration/schema/has-many/accessor-test.js, tests/integration/schema/has-many/create-association-test.js, tests/integration/schema/has-many/has-many-helper.js, tests/integration/schema/has-many/instantiating-test.js, tests/integration/schema/has-many/new-association-test.js, tests/integration/schema/has-many/set-association-ids-test.js, tests/integration/schema/has-many/set-association-test.js
just a small one found when setting a hasMany with the ORM.
=> missing camelize

addon/orm/schema.js, addon/route-handlers/shorthands/delete.js, addon/route-handlers/shorthands/get.js, addon/route-handlers/shorthands/post.js, addon/route-handlers/shorthands/put.js, addon/serializer-registry.js, addon/serializers/json-api-serializer.js
=> Rename `type` to `camelizedModelName`

tests/index-named-imports-test.js
=> tests to check for presence of named exports

addon/serializer-registry.js, tests/integration/serializers/base/full-request-test.js
This relies on the "fix" in #515.
Based on the very last code snippet you added here: https://github.com/samselikoff/ember-cli-mirage/pull/271#issuecomment-138127734, I added an optional function at `Serializer.includesForRequest(request)` that, if it's defined, gets preference over the static `Serializer.include` prop.
I just arbitrarily picked a name and made it an optional function (so it's a non-breaking change), but tell me whatever you'd ideally like and I'll tweak the PR.
I'll also re-check the old #266 and #270 issues now that I'm using 0.2.0-beta.
=> Includes takes an optional function

ember-cli-build.js, index.js
Closes #524 
It depends on / contains #541 (you can merge only this one and close the other if you want)
Honestly, I have no idea how to write a test for this.
=> Fix addon integration

addon/db-collection.js, addon/orm/schema.js, addon/route-handler.js, addon/route-handlers/shorthands/base.js, addon/route-handlers/shorthands/delete.js, addon/route-handlers/shorthands/get.js, addon/route-handlers/shorthands/post.js, addon/route-handlers/shorthands/put.js, addon/server.js, tests/integration/route-handlers/delete-shorthand-test.js, tests/integration/route-handlers/get-shorthand-test.js, tests/integration/route-handlers/post-shorthand-test.js, tests/integration/route-handlers/put-shorthand-test.js, tests/unit/route-handlers/shorthands/base-test.js
* identifying `modelName` from path not from request url
* moved identifying `modelClass` to constructor
=> Shorthand refactor

addon/route-handlers/shorthands/base.js, tests/unit/route-handlers/shorthands/base-test.js
=> Include belongsTo relationships in _getAttrsForRequest.

blueprints/ember-cli-mirage/index.js, bower.json
Fixes https://github.com/samselikoff/ember-cli-mirage/issues/571
=> Upgrade Pretender to 0.12.0

docs/v0.0.27/acceptance-testing.md, docs/v0.0.28/acceptance-testing.md, docs/v0.0.29/acceptance-testing.md, docs/v0.1.x/acceptance-testing.md
=> fix assert.equal typos

addon/server.js, tests/integration/server/model-creation-test.js
=> Make server.create and server.createList return Models

docs/v0.2.0-beta.7/installation.md
Fixes a broken link to the upgrade guide
=> Fix with a correct upgrade guide link

addon/orm/model.js
First pass on #658 (just the `orm/Model` class for starters)
=> adds YUIDoc comments to Model class

bower.json
Get access to new randomization functions
=> upgrade Faker to 3.1.0

addon/db-collection.js, addon/serializer.js
Continuing on with #658 ! Also, small addition to addon/db-collection to keep tests passing.
I left the examples that were in the previous comments, let me know if you would prefer they be removed (or if I should add the examples from the documentation to these comments).
Also, feel free to let me know if you would prefer I add these to a bunch of files at once instead of one at a time!
(closed the other PR because I have no idea why it kept failing, but this one shouldn't be)
=> adds YUIDoc comments to addon/serializer

docs/v0.2.0-beta.8/models.md
Hey, I _suspected_ today that this would be possible and it was, so this just makes it explicit in the documentation. I’m not sure what the procedure is for documentation-only updates, hopefully this is the correct thing to do!
=> Add multi-attribute update documentation

CHANGELOG.md
Nice work on landing the new serializer setup!
=> Added a missing word to the change log 

docs/v0.2.0-beta.8/serializers.md
Is this where you want docs prs sent?  Let me know if I should send it somewhere else ...
=> Fixing a mistake in one of the serializer examples

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/included-test.js
For now this is just a failing test demonstrating the issue.
Closes #708
=> Serializers can incude related resources using dot-path notation

blueprints/ember-cli-mirage/index.js, bower.json
Pretender is finally stable. Lets use it.
=> Update pretender to 1.1

addon/db-collection.js, addon/db.js, addon/orm/model.js, addon/serializer.js
* continues on #658 
* updates formatting on earlier comments to include `*` on every line
* squashed earlier serializer commit into updated commit because fixing the merge conflict resulted in 2 commits. Seemed better to put them together.
=> adds YUIDoc comments to addon/db.js + updates earlier comments

docs/v0.2.0-beta.8/database.md
Thought we should probably document this functionality, as it'd be really useful to use more regularly ;-)
=> [DOCS] Added information about custom query ability

addon/orm/collection.js
for #658 
I can see that the Travis failure I'm experiencing currently is also on at least one other PR. All tests pass locally, not sure what the Travis error is about (something about lodash?).
=> adds YUIDoc comments to orm/collection.js

addon/orm/schema.js
=> adds YUIDoc comments to orm/schema.js

addon/route-handler.js, addon/route-handlers/shorthands/head.js, addon/server.js, tests/integration/route-handlers/head-shorthand-test.js
refers to #723
- returns 204 if resource was found
- returns 404 if a resource was expected to be found but wasn't
=> Add HEAD request route handler shorthand.

docs/v0.2.0-beta.9/defining-routes.md
ApplicationSerializer's file path `application/serializer.js` should be `serializers/application.js`
=> Fix the wrong path of ApplicationSerializer file.

docs/v0.2.0-beta.10/models.md
Pending #795, assuming the feature would be in v0.2.0-beta10
=> Documentation for findBy

docs/v0.2.x/quickstart.md, docs/v0.2.x/serializers.md
Hi! I've noticed a couple of issues with the docs while working though them:
- need a belongsTo relation in a child model, otherwise the factory won't create objects
- wrong object is used in serializer example
=> Doc updates

package.json
See here:
https://nodesecurity.io/advisories/118
=> Update minimatch to avoid vulnerability

addon/orm/associations/belongs-to.js, addon/orm/associations/has-many.js, addon/orm/model.js, addon/orm/schema.js, addon/route-handlers/shorthands/base.js, addon/serializer.js, addon/serializers/rest-serializer.js, addon/server.js, addon/utils/normalize-name.js, tests/integration/orm/collection-inflector-test.js, tests/unit/utils/normalize-name-test.js
=> Introducing utils/normalize-name.js to concentrate the naming logic

docs/v0.2.x/factories.md
Some of the syntax highlighting is missing
=> Added syntax highlighting

addon/orm/associations/has-many.js
Solves https://github.com/samselikoff/ember-cli-mirage/issues/773
=> add YUI docs to hasMany

addon/orm/associations/belongs-to.js
Wanted to learn about the internals of the addon and thought I could add some YUI docs if already needed, solves https://github.com/samselikoff/ember-cli-mirage/issues/774.
=> add YUI docs for belongsTo

package.json
=> peg faker at 3.0.1

addon/server.js
=> Improve the format of the logging message

_includes/resource-shorthands-code-compare.html, docs/v0.2.x/shorthands.md
Docs for `resource` helper from: https://github.com/samselikoff/ember-cli-mirage/pull/814
=> [DOCS] add docs for :resource helper

docs/v0.2.x/factories.md
=> Fixed a spelling mistake in the new traits section

docs/v0.2.x/route-handlers.md
as per the discussion on samselikoff/ember-cli-mirage#847
=> Add note about ES6 arrow functions

tests/unit/server-test.js
See: pretenderjs/pretender#178
=> Shutdown pretender servers in unit tests

docs/v0.2.x/route-handlers.md
=> [DOCS] Add example using a promise in a handler function

addon/factory.js, tests/unit/factory-test.js, tests/unit/server-test.js
=> Fix factories are instantiated with attributes undefined

CHANGELOG.md
Happy to work on the wording of this
=> update changelog to reflect changes to faker dependency

addon/route-handlers/base.js, tests/unit/route-handlers/shorthands/base-test.js
Opening this up re: https://github.com/samselikoff/ember-cli-mirage/issues/885 I'm not sure it's sufficient enough - I don't have enough context of the entire codebase, but wanted to at least get something started to help out.
=> Adds single test case to allow payload with type

docs/v0.2.x/factories.md
contacts.length => contacts.models.length
```contacts.isAdmin = false``` => ```contacts.update({ isAdmin: false })```
see also #948
=> server.contacts => server.schema.contacts

addon/server.js
=> refactor(server): add default passthrough for electron's localhost socket server

.travis.yml, blueprints/ember-cli-mirage/index.js, bower.json, package.json
This prevents the termination of the process and updating these files from racing.
=> [BUGFIX] Blueprint.prototype.insertIntoFile is async

addon/server.js, ember-cli-build.js, tests/unit/server-test.js
A quick PR fixing this issue: https://github.com/samselikoff/ember-cli-mirage/issues/790
=> throw error if the second argument of buildList or createList is not an integer

docs/v0.2.x/collections.md
@samselikoff I came across #858, and wanted to follow up with [your documentation request](https://github.com/samselikoff/ember-cli-mirage/pull/858#issuecomment-244524427).
Cheers 😄.
=> Document Collection.sort and Collection.filter

blueprints/ember-cli-mirage/files/__root__/config.js
There is not really much more to say about this except thanking you for the work :)
=> Update link in blueprint

blueprints/ember-cli-mirage/index.js
minor styling issue: there's a whitespace missing
=> add missing space in conditional

docs/v0.3.x/serializers.md
Fixed a small mistake in the name of Serializer in docs
=> Fix mistake with name of serializer

.npmignore
From this image, note ".sass-cache", "jekyll-tmp", "CONTRIBUTING.md", and "ISSUE_TEMPLATE.md"
=> ignore artifacts in npm

blueprints/ember-cli-mirage/index.js
Since the file in /tests inherits from the root file, it doesn't seem necessary to add it there too.
=> only update root lint file

addon/serializer.js, tests/integration/serializers/base/override-serialize-test.js
A PR for issue #1103 
Please let me know if I'm in the right direction or need to add/remove things cc @samselikoff
=> Expose database in serializer

.jshintrc, .travis.yml, addon/db-collection.js, addon/factory.js, addon/orm/associations/belongs-to.js, addon/orm/associations/has-many.js, addon/orm/collection.js, addon/orm/schema.js, addon/route-handler.js, addon/route-handlers/shorthands/base.js, addon/serializer-registry.js, addon/serializer.js, addon/server.js, addon/utils/extend.js, addon/utils/read-modules.js, app/initializers/ember-cli-mirage.js, blueprints/ember-cli-mirage/index.js, bower.json, index.js, package.json
I have several projects on the 0.1.x branch that I have not had time to upgrade yet
This PR removes the bower lodash dependency on that branch so that I can remove the bower lodash dependency from projects still on 0.1.x.
=> Remove lodash dependency from 0.1.x branch.

addon/db-collection.js, addon/db.js, addon/identity-manager.js, addon/index.js, addon/server.js, addon/utils/read-modules.js, blueprints/mirage-identity-manager/files/__root__/identity-managers/__name__.js, blueprints/mirage-identity-manager/index.js, tests/acceptance/contact-test.js, tests/acceptance/edit-test.js, tests/acceptance/identity-manager-test.js, tests/dummy/mirage/identity-managers/author.js, tests/dummy/mirage/models/author.js, tests/index-named-imports-test.js, tests/integration/db/identity-manager-test.js, tests/unit/db-test.js, tests/unit/db/identity-manager-test.js
Adds support for custom identity managers per application and/or per model as asked for in #960. PR is based on v0.3.0-beta.4.
=> custom identity managers per application and/or model

.travis.yml
=> fix master

.travis.yml
looks like this got lost in #1128 too...
=> CI: Use yarn to install bower

.gitignore, .npmignore, bower.json, package.json, testem.js, tests/test-helper.js, yarn.lock
... and remove a few obsolete dependencies in the process.
=> Update "ember-cli" and "ember-cli-qunit"

package.json, yarn.lock
Closes https://github.com/samselikoff/ember-cli-mirage/pull/1125
/cc @cibernox
=> Update to Babel 6

addon/route-handler.js, addon/server.js, addon/utils/inflector.js, addon/utils/read-modules.js, app/initializers/ember-cli-mirage.js, fastboot-tests/fixtures/fastboot/app/router.js, tests/acceptance/custom-handlers-test.js, tests/acceptance/manually-starting-test.js, tests/dummy/app/app.js, tests/dummy/app/controllers/application.js, tests/dummy/app/router.js, tests/dummy/app/routes/application.js, tests/dummy/app/routes/close-friends.js, tests/dummy/app/routes/contacts.js, tests/dummy/app/routes/friends.js, tests/dummy/app/routes/pets.js, tests/dummy/mirage/config.js, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/start-app.js, tests/integration/route-handlers/function-handler-test.js
see https://github.com/ember-cli/ember-rfc176-data
=> Use "New Module Imports" instead of destructuring

docs/v0.3.x/upgrading.md
or use full path this might also works
````
[0-3 beta series release blog post](/blog/2017/01/09/0-3-0-beta-series/)
````
=> use url for blog post

blueprints/mirage-serializer/files/__root__/serializers/__name__.js
=> serializer blueprint should extend the application serializer

addon/server.js, tests/integration/server/resource-shorthand-test.js
=> feat: can pass singular model name to resource helper

tests/helpers/promise-ajax.js, tests/integration/http-verbs-test.js, tests/integration/passthrough-test.js, tests/integration/route-handlers/function-handler-test.js, tests/integration/serializers/base/full-request-test.js, tests/integration/server/custom-function-handler-test.js, tests/integration/server/customized-normalize-method-test.js, tests/integration/server/resource-shorthand-test.js, tests/integration/server/shorthand-sanity-test.js
Wraps Ajax with a promise... Paves the way for `async/await`... paves the way to drop in fetch in the future maybe.
=> Promise ajax

CHANGELOG.md
This wasn't the right link previously
=> Updated changelog with an accurate link

index.js, node-tests/addon-tree-test.js, package.json, yarn.lock
This is my first attempt at addressing #1210.
@rwjblue would you be up for taking an initial peak at what I have so far? I have taken a pretty simple approach to start with here. This is also the first time that I have attempted to write a test(s) to cover the state of a broccoli tree. Any / insight feedback would be appreciated. Thank you in advance.
=> Add noop initializer when mirage is excluded from build

docs/v0.4.x/acceptance-testing.md
=> Fix qunit assertion. Format route name.

blueprints/ember-cli-mirage/index.js
This code wasn't matching the new blueprint style.
=> match new blueprint

addon/orm/model.js, tests/integration/orm/mixed/3-one-to-many-polymorphic/_helper.js, tests/integration/orm/schema-verification/mixed-test.js
Refactor the inverseFor code to run a different set of checks if the there
is an explicit inverse defined.
=> Add inverse for polymorphic relationships

addon/serializer.js, tests/integration/serializers/base/associations/embedded-model-test.js
This branch has the fix from #1224 and the requested test for validation. This fixes issue #1223.
🤖
=> [1223] - fix to allow null value for belongsTo and test

docs/v0.4.x/acceptance-testing.md
After having difficulty with setting up acceptance tests myself, I recieved support in the slack channel. I figured that I would update the docs myself to ensure it's not an issue for others in the future.
=> correct acceptance testing docs

addon/server.js, tests/integration/passthrough-test.js
HEAD is missing in the default list of allowed verbs.
=> Allow passthrough HEAD

tests/unit/server-test.js
=> fix test name

addon/serializer.js, tests/integration/serializers/base/associations/polymorphic-has-many-test.js
Allows embedding of included polymorphic hasMany items.
=> Fixes #1175 - Error when embedding included polymorphic hasMany items

addon/server.js
* Default message stays the same
* Groups logs using `console.groupCollapsed`
* Adds request to logged data
* Adds "raw" request to logged data
Demo: https://www.youtube.com/watch?v=qV_HlRnvKZk
=> Enhance log messages

addon/serializer.js, tests/integration/serializers/base/associations/polymorphic/belongs-to-test.js, tests/integration/serializers/base/associations/polymorphic/has-many-test.js
=> [fixes #1274] Fix relationship ID bug for polymorphic includes

addon-test-support/setup-mirage.js
Co-authored-by: Peter Wagenet <peter.wagenet@gmail.com>
=> Fix teardown when pending requests

addon/serializer-registry.js, addon/serializer.js, tests/integration/serializers/base/associations/polymorphic/top-level-test.js, tests/integration/serializers/json-api-serializer/associations/polymorphic-test.js
Closes https://github.com/samselikoff/ember-cli-mirage/issues/1242
=> Serialize top-level polymorphic collections

addon/response.js, addon/route-handlers/shorthands/delete.js, addon/server.js, tests/integration/server/shorthands/active-model-serializer-sanity-test.js
- Data defaults to empty string
- Closes https://github.com/samselikoff/ember-cli-mirage/issues/1295
=> Only add Content-Type to responses with data

addon/serializers/json-api-serializer.js, tests/integration/server/regressions/1322-relationship-path-normalization-test.js, yarn.lock
It's just a continuation of #1323 adding support for nested includes (`?include=happy_user.happy_avatar`). I moved the dasherization to the very beginning of the includes graph building process.
First commit adds a failing test, second - the solution.
=> Nested include normalization

docs/v0.4.x/configuration.md
- Remove all the occurrences of `app/` as a prefix for example file paths because it's not the default now.
=> Update paths in configuration.md

tests/integration/orm/has-many/3-reflexive/accessor-test.js, tests/integration/orm/has-many/3-reflexive/new-test.js, tests/integration/orm/has-many/4-named-reflexive/accessor-test.js, tests/integration/orm/has-many/4-named-reflexive/new-test.js, tests/integration/orm/has-many/5-named-reflexive-explicit-inverse/accessor-test.js, tests/integration/orm/has-many/5-named-reflexive-explicit-inverse/new-test.js, tests/integration/orm/has-many/6-one-way-reflexive/accessor-test.js, tests/integration/orm/has-many/6-one-way-reflexive/new-test.js, tests/integration/orm/has-many/7-named-one-way-reflexive/accessor-test.js, tests/integration/orm/has-many/7-named-one-way-reflexive/new-test.js, tests/integration/orm/has-many/8-many-to-many/accessor-test.js, tests/integration/orm/has-many/8-many-to-many/new-test.js, tests/integration/orm/mixed/1-one-to-many/accessor-test.js, tests/integration/orm/mixed/1-one-to-many/instantiating-test.js, tests/integration/orm/mixed/2-many-to-one/accessor-test.js, tests/integration/orm/mixed/3-one-to-many-polymorphic/accessor-test.js, tests/integration/orm/mixed/3-one-to-many-polymorphic/instantiating-test.js
Gets the tests passing in IE11. Based on feedback in #1391.
=> Fix tests in IE11

addon/server.js
Believe this needs to be `this.urlPrefix` instead of the existing `this.prefix`.
=> Fix prefix example code

addon/orm/model.js, tests/integration/orm/belongs-to/11-named-one-way-reflexive-self-referential/_helper.js, tests/integration/orm/belongs-to/11-named-one-way-reflexive-self-referential/accessor-test.js, tests/integration/orm/belongs-to/11-named-one-way-reflexive-self-referential/association-create-test.js, tests/integration/orm/belongs-to/11-named-one-way-reflexive-self-referential/association-new-test.js, tests/integration/orm/belongs-to/11-named-one-way-reflexive-self-referential/association-set-id-test.js, tests/integration/orm/belongs-to/11-named-one-way-reflexive-self-referential/association-set-test.js
closes https://github.com/samselikoff/ember-cli-mirage/issues/1479
=> fix: reflexive relationships can be self-referential

addon/serializer.js
=> Document keyForForeignKey method

package.json, vendor/ember-cli-mirage/pretender-shim.js, yarn.lock
~- [ ] depends on the release of Pretender v3.0.0 (pending https://github.com/pretenderjs/pretender/pull/248)~
=> remove Pretender shim

tests/dummy/app/pods/docs/getting-started/installation/template.md
With the ember serve command that lets people work around the issue
=> Add incompatibility with Fastboot notice to docs

CONTRIBUTING.md, addon/orm/schema.js, tests/unit/schema-test.js
Attempts to fix #1567.
Not quite sure if the tests are located where they should be. Happy to revisit with a little guidance.
I also removed `bower i` from CONTRIBUTING.md since when I copied the command it "errored" since there is no bower.json file anymore.
=> Tests coverage for Schema.first() and Schema.findBy()

package.json, yarn.lock
Full description of issue: https://github.com/ember-cli/ember-try/issues/360#issuecomment-500969714
=> Fix issue with segaults during Travis builds

package.json, yarn.lock
Closes https://github.com/samselikoff/ember-cli-mirage/issues/1641
=> Bump mirage

addon/server.js, package.json, tests/dummy/app/pods/docs/data-layer/models/template.md, tests/dummy/app/pods/docs/data-layer/orm/template.md, tests/dummy/app/pods/docs/data-layer/relationships/template.md, tests/dummy/app/pods/docs/template.hbs, tests/dummy/app/router.js, yarn.lock
Closes https://github.com/samselikoff/ember-cli-mirage/issues/1665
=> Add docs on models and relationships, and bump server

tests/dummy/app/pods/docs/testing/acceptance-tests/template.md
=> Update template.md for typo

tests/dummy/app/pods/docs/data-layer/serializers/template.md, tests/dummy/app/pods/docs/getting-started/overview/template.md
I was able to access the desired pages via the sidebar, but might as well remove that moment of confusion. 💞
=> Fix broken intra-documentation links

tests/dummy/app/pods/docs/data-layer/relationships/template.md
=> Fix relationship links

tests/dummy/app/pods/docs/advanced/customizing-the-inflector/template.md
=> Update Customizing the inflector docs [2]

package.json
Fixes #2020
no lockfile change needed
=> revert public dep updates that removed node 8

tests/dummy/app/pods/docs/data-layer/serializers/ember-data-serializer/template.md
~(Date -> Data)~
Updated to a working example.
=> Fix import example for EmberDataSerializer

addon/instance-initializers/ember-cli-mirage-autostart.js, package.json
This better aligns with Ember Octane mental model
=> Use @ember/destroyable for mirage server shutdown

package.json, tests/dummy/config/addon-docs.js, tests/dummy/config/deploy.js, yarn.lock
Solves this issue https://github.com/ember-learn/ember-cli-addon-docs/pull/1137 which is not released yet.
=> Bump `@embroider/*` packages to latest

packages/ember-cli-mirage-docs/app/models/comment.js, packages/ember-cli-mirage-docs/app/models/word-smith.js, packages/ember-cli-mirage/tests/dummy/app/models/comment.js, packages/ember-cli-mirage/tests/dummy/app/models/post.js, packages/ember-cli-mirage/tests/dummy/app/models/word-smith.js, packages/ember-cli-mirage/tests/unit/models/ember-data-model-discover-test.js
#2503 is known issue. This PR adds tests so we could verify if it gets resolved moving forward.
=> Add tests for discoverEmberDataModels function

packages/ember-cli-mirage/config/environment.js
=> Restore usingProxy config
