app/ember-pretenderify/config.js
Using `Function.prototype.bind` makes this fail on Phantom 1.x (unless you polyfill).  This was the only instance, and seems to be fairly easy to remove the `bind`, so I think it makes sense to make this easier to consume.
=> Remove usage of `Function.prototype.bind`.

addon/controllers/delete.js, addon/controllers/get.js, addon/controllers/post.js, addon/controllers/put.js, addon/inflector.js, addon/store.js, blueprints/ember-pretenderify/index.js, bower.json, index.js, tests/unit/inflector-test.js
`ember-inflector` is used by Ember Data, but we should pull it in
manually so that it does work without Ember Data.
=> Enable usage without Ember Data.

index.js, package.json, tests/.jshintrc, tests/fixtures/config/environment-with-force-true.js, tests/unit/addon-tree-test-node.js, tests/unit/import-files-test-node.js
In order to test this behaviour I added some files ending with `*test-node.js` which will be tested in the node context using mocha. I tried to not touch so much the ember-cli internals, since testing these file inclusions isn't so clear, but if something changes in the next ember-cli versions, the tests will point out.
//cc @samselikoff 
Fixes #17
=> Don't include files in production build

index.js, tests/unit/addon-tree-test-node.js
By default ember-cli includes anything found in [`app/*`](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L206) dir like `app/pretender`. To get around this we can remove the `app/pretender` from the app tree using broccoli-funnel when it's not needed.
Fixes #17
=> Remove app/pretender dir in production builds

addon/server.js, tests/acceptance/timing-test.js, tests/unit/server-test.js
Motivation:
I have some acceptance tests where I want to tests that if the server
take too long to respond, a message of "Loading more data" is displayed.
Making the interceptor respond without delay in tests is a reasonable
default but for my use case made some things untestable.
What I wanted was to allow in specific tests to set `server.timing = 1000`
and then restore the old value. Example:
```js
module('Acceptance: Slow Filtering', {
beforeEach: function() {
server.timing = 1000;
application = startApp();
server.createList('posts', 21);
},
afterEach: function() {
server.timing = 0;
Ember.run(application, 'destroy');
}
});
test('when the server takes too much to respond a loading message is displayed', function(assert) {
// Some test
});
```
That was not possible because the route …
=> Allow to modify the server timing in runtime.

blueprints/ember-cli-mirage/files/app/mirage/config.js
I noticed the config.js was using an old version of the db API, updated the syntax/methods to reflect the new one.
I'm not sure if {collection} is the best way to express what's happening, but I think between the comment on line 55 and the example function the intent should be clear.
=> Update config.js examples with new db API

README.md
The ember cli addon command was changed in the latest version. I'm making the assumption that the readme always assumes the user is using the latest ember-cli version. :smile:
=> Updates readme to use the latest ember-cli command.

addon/controllers/base.js, tests/unit/base-controller-test.js
I have a model that has an id with dashes in it. When trying to model this in mirage, I noticed that it grabbed the id with just the first number.
I added a couple of tests for my edge case (where `2-1` was the id which resolved to `2`)
I'd love to see this merged, but if there's something that I'm overlooking, just let me know!
=> Update base controller id coercion

index.js, package.json
This switches to using broccoli-merge-trees directly instead of the deprecated `this.mergeTrees`. I also added broccoli-funnel.
=> Updates to use broccoli-merge-trees.

.npmignore
The Size of this addon on npm registry is pretty big (~188MB) because of packaged `tmp` folder.
=> Add tmp directory to npmignore

addon/db.js, addon/shorthands/utils.js, tests/unit/db-test.js
Mirage was parsing ids like "123-456" like "123". That is not correct.
Now only tries to parse the ID as an integer if its a String that looks like an Interger.
=> [WFA] More clever ID parseInt

addon/db.js, tests/unit/db-test.js
I found that `db.contacts.update('123-abc', { name: 'new-name' })` didn't work.
Now it does :)
=> [WFA] Fix update for records with string ids.

addon/controller.js, tests/acceptance/custom-handlers-test.js, tests/dummy/app/mirage/config.js, tests/dummy/app/mirage/factories/pet.js, tests/dummy/app/models/pet.js, tests/unit/controller-test.js
When a custom handler of an action that by default returns a 204 status
generates a non-blank response, a status 200 is used instead. 
Also added high-level acceptance tests for custom handlers
=> [WFA] Change status 204 to 200 when response is present

addon/server.js
I was finding
difficult for my brain. This pull request makes the message look like this instead
=> Decode the failed URI before logging it

blueprints/ember-cli-mirage/index.js
Just added ember-cli-mirage to another project.
Too lazy to add `server` to my jshintrc, somehow not too lazy to put this together.
=> Automatically add server to jshintrc files

addon/db.js, tests/unit/db-test.js
Fixed issue where removing all records from the collection would not allow you to add new ones afterwards.
The collection would no longer have the methods on it anymore because it was just set back to an empty array. By calling `createCollection` again it clears the collection's array and also adds the methods back on it as well.
@samselikoff What do you think?
=> Fix removing all records then adding new ones

addon/controller.js, addon/server.js, addon/shorthands/get.js, tests/acceptance/friends-test.js, tests/dummy/app/mirage/config.js, tests/dummy/app/router.js, tests/dummy/app/routes/close-friends.js, tests/dummy/app/templates/close-friends.hbs, tests/unit/shorthands/get-test.js
Now shorthand methods can receive a POJO with options, ignored by all
shorthands except of the `get` one.
The `get` handler supports the `coalesce` option, which defaults to
false. When enabled that option will make the shorthand method look for
an `ids` attribute on the queryParams, and will return with a collection
containing only the models with those ids.
Examples:
```js
this.get("/contacts", { coalesce: true }); // "/contacts?ids=1,3]"
this.get("/friends", "users", { coalesce: true }) // "/friends?ids=2,4"
```
=> Coalesce find requests in get shorthand handlers

addon/shorthands/utils.js, tests/unit/shorthands/utils-test.js
For example: '/api/properties/?ll=42.426894%2C-71.046524' 
That was not handled previously.
=> Handling urls types with slash before ?

addon/db.js, tests/unit/db-test.js
Having this records in the db:
```js
[
{ id: 1, name: 'Bob', teacher_id: 123},
{ id: 2, name: 'Jane', teacher_id: 234}
]
```
performing a query like `/students?teacher_id=123` would return no
result because queryParameters in the requests are always treated as
strings, and `db.students.where({teacher_id: req.queryParams.teacher_id})`
will compare using `===`.
Now `where` coherces both operands to string before comparing them,
returning the expected student.
This also makes true === "true" and such, but that is very unlikely to cause
any problem.
=> Where coherces query parameters to strings

app/initializers/ember-cli-mirage.js, tests/acceptance/friends-test.js, tests/dummy/app/mirage/config.js, tests/dummy/app/router.js, tests/dummy/app/templates/friend.hbs
First, here's the use case this is solving. The app is already existing and is set up with `--proxy`, so mirage needs to be explicitly enabled.
Workflow:
1. Create fixtures/factories for new feature development.
2. Stop using the fixtures in development when the API is ready, but keep using the factories in tests. This assumes a passthrough fallback is in place, either manually or from #134 so mirage doesn't complain about the route not being defined.
I can't think of a way to do this without requiring an update of some sort to consuming apps, and the approach here seems the least invasive. I can do this manually by adding `if (environment === 'test')` around test only routes, but it's messy. I also need to do this across at least 3 apps, and assume some others might be in a similar boat. …
=> Add ability to have per environment configs.

.npmignore
Add .sass-cache, _site and jekyll-tmp folders to .npmignore as their size is ~ 120MiB
=> Add npm unrelated folders to .npmignore

addon/server.js
Replace `Array.insertAt` by `Array.splice`.
Note: this make it possible to use `ember-cli-mirage` for addons.
=> Use splice instead of insertAt

docs/latest/defining-routes.md, docs/v0.0.27/defining-routes.md, docs/v0.0.28/defining-routes.md, docs/v0.0.29/defining-routes.md
This caught me out earlier today. Just a typo, I think.
Thanks for this great project!
=> Query params are accessed via request.queryParams

.travis.yml, config/ember-try.js, tests/dummy/app/routes/contacts.js
I was trying to track down the build failures for #175 and I discovered that on master the "ember-beta" scenario is also failing. It appears to be failing because in that scenario ember-data attempts to read off `indexOf` from `Ember.EnumerableUtils.indexOf`, which no longer exists in ember beta.
This makes a few changes:
* adds the ember 1.13.2 scenario which also uses ember-data 1.13.2
* I had to make a small change to the dummy app contacts route error
handler to account for a difference in the way ember-data 1.13.2
handles exposes errors (it no longer passes through the jqXHR)
* Change travis.yml to allow the ember-beta scenario to fail. It is failing anyway because `ember#beta` now points at ember 2.0, whereas when v0.1.4 of mirage was released beta was pointing at 1.13, and that's …
=> Add ember 1.13.2 scenario

app/initializers/ember-cli-mirage.js
This fixes #174. It relies on the now-private `Ember.keys` api, unfortunately, but this seems as though it should do the job.
=> [closes #174] Check if `modulesMap['factories']` is empty via Ember.keys

blueprints/ember-cli-mirage/files/app/mirage/factories/contact.js, blueprints/ember-cli-mirage/files/app/mirage/scenarios/default.js
To reproduce:
```
ember new my-app 
cd my-app
ember install ember-cli-mirage
ember test
```
``` bash
JSHint - mirage/factories: mirage/factories/contact.js should pass jshint
✘ mirage/factories/contact.js should pass jshint.
mirage/factories/contact.js: line 6, col 17, 'faker' is defined but never us
ed.
....
JSHint - mirage/scenarios: mirage/scenarios/default.js should pass jshint
✘ mirage/scenarios/default.js should pass jshint.
mirage/scenarios/default.js: line 1, col 25, 'server' is defined but never u
sed.
```
=> Default mirage config was fail the tests

addon/shorthands/get.js, tests/unit/shorthands/get-test.js
p.e: `/users/999` now returns `new Mirage.Response(404, {}, {})` when
the user with that id is not in the database
=> Shorthand method with id return 404 when record is missing

addon/shorthands/get.js
The undefined handlers can infer the type and just invoke the string handler with it, since the behaviour is the same.
=> Reuse code between undefined and string get shorthands

README.md
This adds a sub-section to the Installation section that lets users
know that they need to add ember-cli-es5-shim to their project
if they are using PhantomJS < 2.0 because of the use of 
`.bind` in Mirage.
The credit for this really goes to @samselikoff for helping me
with this! 😁
=> Add es5 polyfill requirement to the README

bower.json
This should fix most of the memory leak happening in acceptance tests.
Tomorrow I'll perform some more checks to see if there is still
something leaking in my test suite, and is so apply some voodoo I've
learnt today.
=> Depend on pretender 0.9

addon/server.js
I keep my fight agains memory leaks. This one removes the server (and the internal pretender too) when the server is shut down.
=> Release window.server global on shutdown

addon/utils/inflector.js, bower.json, index.js, package.json
- Also updates ember-inflector from version 1.3.1 to 1.9.0
- Prevents installing `ember-cli-mirage` from breaking the build with the latest Ember canary (the reference to `Ember.Handlebars` in the old version of `ember-inflector` was messing with things)
Closes #221
=> Install ember-inflector from NPM

blueprints/factory/files/app/mirage/factories/__name__.js
JSHint complains about unused {faker} import in default factory.
=> Update factory blueprint to pass JSHint

blueprints/ember-cli-mirage/index.js
We changed it in `package.json` but not here.
=> Ensure consuming apps depend on pretender 0.9

addon/server.js, blueprints/ember-cli-mirage/files/app/mirage/config.js, tests/integration/server-config-test.js
With Pretender v0.9.0 now supporting fully-qualified URLs, this update adds the ability to use FQDNs in your route configurations. It also adds a new `urlPrefix` parameter that allows you to configure Mirage to prepend a FQDN to all of your route configurations automatically.
=> Adds support for FQDN in route configuration 

docs/v0.1.x/database.md
The db.users.where clause was not returning an existing user in the db according to the 'Givens'. We want the documentation to match the 'Given' users for a clear example.
=> Fix WHERE db method example

docs/v0.0.27/server-configuration.md, docs/v0.0.28/server-configuration.md, docs/v0.0.29/server-configuration.md, docs/v0.1.x/server-configuration.md
This took me some time to figure out and find in the issues. I suppose this is something that a lot of people need (passthrough option) and might run into.
=> Warn that passthrough only works with jQuery > 2.x

docs/v0.1.x/manually-starting-mirage.md
This caused my jshint to warn me when I dropped it into my app.
The [spec](http://ecma262-5.com/ELS5_HTML.htm#Section_13) to back this up.
=> (Docs) Function declarations should not be followed by semi-colons

app/initializers/ember-cli-mirage.js
Ember 2.1 introduces the following deprecation message:
https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application.js#L607
This avoids that message in a backward compatible manner.
=> Avoid deprecation warning in Ember.js 2.1

addon/db-collection.js, addon/db.js, tests/unit/db-test.js
A common pattern I was seeing in our Mirage config was the need to
either find the first record matching a certain query, or to create it.
This change introduce `DbCollection#firstOrCreate`. It returns the first
record that matches a query, or creates it if need be.
=> [FEATURE] `DbCollection#firstOrCreate`

blueprints/ember-cli-mirage/index.js
Changes from version 0.9 include better synchronous xhr support, some fixes for content-type header and event firing on `passthrough`'d requests, better error messages.
See the changes from Pretender 0.10.0 -> 0.10.1 [here](https://github.com/pretenderjs/pretender/blob/master/CHANGELOG.md).
=> Update Pretender version to ~0.10.1

docs/v0.1.x/routes.md
A typo fix
Because it resulted in using an incorrect setting for the site URL prefix
=> Fixed a typo in setting this.urlPrefix

CHANGELOG.md, addon/server.js
While TDDing, test failure feedback is very important. We prefer loud
failures of quiet ones.
Unfortunately, `console.log` won't cause a test failure while running
`ember test --serve`. If a Mirage route is undefined, tests tend to
hang.
Upon further investigation in a UI-backed browser like Chrome or
Firefox, the `console.log` message is visible.
This feedback is still useful, but we'd prefer to see it in the console,
without having to resort to a visual browser.
=> Throw an Error when Mirage route is not defined

README.md, addon/db.js, addon/orm/schema.js, ember-cli-build.js, package.json, tests/index.html
Removing usage of `function.prototype.bind` means we can get rid of es5-shim.
=> remove dev dependency on es5-shim

package.json
ember-lodash is always needed -- not just when ember-cli-mirage is under development.
=> Make lodash a runtime dependency

addon/orm/schema.js, tests/integration/schema/reinitialize-associations-test.js
Model classes with associations can only be correctly registered with a Schema once, because the registration process mutates them. This change extends them instead so that we don't mutate the originals.
I needed to switch to `for ... in` instead of `Object.keys` because now we definitely need to walk the prototype chain to find associations. This was probably a separate latent bug, since users can put associations onto ancestor classes.
=> Don't mutate model classes

addon/serializer-registry.js, tests/integration/serializers/base/serialize-array-of-models-test.js
This ensures that we will correctly serialize any array of `Model`. It's helpful because many natural transforms of `Collection` do not result in a new `instanceof Collection`. For example:
schema.posts.all().filter(post => post.upVotes > 100)
Without this change, an example like the above returns unserialized results.
=> Apply serializer to any array of Model

addon/utils/read-modules.js
This doesn't break any tests, although [this discussion](https://github.com/samselikoff/ember-cli-mirage/pull/354#issuecomment-153162997) suggests it is probably a breaking change.
This change is necessary to load fixtures for dash-containing model names.
=> camelize module names

addon/route-handler.js, addon/route-handlers/shorthands/delete.js, addon/route-handlers/shorthands/get.js, addon/route-handlers/shorthands/post.js, addon/route-handlers/shorthands/put.js
In the same spirit as [#329].
> While TDDing, test failure feedback is very important. We prefer loud
> failures of quiet ones.
>
> Unfortunately, `console.log` won't cause a test failure while running
> `ember test --serve`. If a Mirage route is undefined, tests tend to
> hang.
> Upon further investigation in a UI-backed browser like Chrome or
> Firefox, the `console.log` message is visible.
> This feedback is still useful, but we'd prefer to see it in the
>  console, without having to resort to a visual browser.
[#329]: https://github.com/samselikoff/ember-cli-mirage/pull/329
=> Throw Errors instead of `console.error`

package.json
This release includes a fix for nested dependencies with Node and
NPM3+ (see mike-north/ember-lodash#7).
=> Bump ember-lodash

addon/orm/model.js
When saving a model with a `null` relationship, mirage throws an error. This allows nullable relationships using `Mirage.Model`. I'm not sure how to test this change.
=> Check if relationship exists before trying to persist

docs/v0.1.x/manually-starting-mirage.md
Ensure that in both the component test and the helper we use the same `startMirage` function name.
=> use startMirage function consistently

docs/v0.1.x/factories.md
This addition means that there is the stated space between `User` and the sequence-generated "id" in the `name` function.
I know this is a tiny nit-pick but it caught my eye!  I hope this is a reasonable (tiny tiny _tiny_) contribution to Mirage as I learn the system.
=> Add space in Factory string

docs/v0.1.x/factories.md
It appears that Markdown-style links do not work within HTML tags.  Use HTML
instead!
=> Make link to issue via HTML anchor tag.

docs/v0.1.x/server-configuration.md, docs/v0.2.x/configuration.md
This fixes what appears to be missed capitalization when splitting a long sentence into more tractable ones.
=> Fixup some small capitalization mistakes

addon/factory.js, tests/unit/server-test.js
Recursively copies nested properties and calls nested functions in the factory definition. Not always as robust as factory relationships. But sometimes your API response format is trivially nested, and this gets ember-cli-mirage to match it quickly. Fixes #206.
=> Allow nested factory objects

docs/v0.2.x/factories.md, docs/v0.2.x/manually-starting-mirage.md
This is a series of changes made to the v0.1.x docs that should probably be merged into the upcoming release docs.
I did not _back_ update to prior versions but could do the same if that's appropriate?
=> Port #429, #430, and #431 to the v0.2.x docs

CHANGELOG.md, blueprints/ember-cli-mirage/index.js, package.json
Ember-CLI 1.13.9 and beyond will have a destroy-app helper that we can shutdown the server in.
This patch automatically inserts this behavior, or shows a message if the user doesn't have a destroy-app helper explaining how to fix the problem.
Fixes #226.
=> Shutdown the pretender server on destroyApp.

addon/server.js, tests/acceptance/custom-handlers-test.js, tests/integration/response-string-test.js
```javascript
this.get('/historydata/', function() {
return new Mirage.Response(200, {'Content-Type': 'text/csv'},"firstname,lastname\nbob,dylon");
});
```
was being send as `""firstname,lastname\nbob,dylon""` with extra quotes around them, this fixes it
=> fixes issue with quotes when body is string

.gitignore, addon/orm/model.js, addon/serializer-registry.js, addon/serializer.js, addon/serializers/json-api-serializer.js, addon/utils/read-modules.js, bower.json, package.json, tests/dummy/app/initializers/es2015-polyfills.js, tests/integration/serializers/active-model-serializer-test.js, tests/integration/serializers/base/associations/embedded-collection-test.js, tests/integration/serializers/base/associations/embedded-model-test.js, tests/integration/serializers/base/associations/sideloading-assorted-collections-test.js, tests/integration/serializers/base/associations/sideloading-collection-test.js, tests/integration/serializers/base/associations/sideloading-model-test.js, tests/integration/serializers/base/full-request-test.js, tests/integration/serializers/json-api-serializer/associations/collection-test.js, tests/integration/serializers/json-api-serializer/associations/included-test.js, tests/integration/serializers/json-api-serializer/associations/model-test.js, tests/integration/serializers/json-api-serializer/attribute-key-formatting-test.js, tests/integration/serializers/json-api-serializer/attrs-test.js, tests/integration/serializers/json-api-serializer/base-test.js, tests/integration/serializers/schema-helper.js, tests/unit/serializers/json-api-serializer-test.js
JSONAPI [recommends](http://jsonapi.org/recommendations/#naming) to use dasherized types. Though not a strict requirement, that's what Ember uses. Ember ignores camel-cased types.
You said the convention is to use camel case in property keys and dashes in strings. It sucked to write `relationships: ['fooBar']`. I refactored the serializer layer to work with `relationships: ['foo-bar']`.
Now JsonApiSerializer combines relationship names from `serializer.relationships` and `request.queryParams.include`.
According to jsonapi.org, a resource object **MAY** contain a relationships object. However, members of the relationships object ("relationships") are said to "represent references from the resource object in which it's defined to other resource objects". I. e. it is not said that …
=> 🎉 Support for `included` query param in JsonApiSerializer

addon/db-collection.js
Using lodash's `assign` method, we can improve the performance of
duplicating objects. A naive benchmark shows that lodash's `assign`
is considerably faster than the previous approach:
https://jsperf.com/object-dup/2
=> Improve Collection Duplication

addon/db-collection.js, tests/unit/db-test.js
We were tracking the _next_ value, not the currently used value. Ugh... I should have caught this :/
=> Fixes a Subtle ID Tracking Bug

addon/serializer-registry.js, addon/serializers/json-api-serializer.js
since `_serializerFor` using just `model name` to find serializer, I think it would be better to pass just modelName to it. Also since `isModel` and `isCollection` not related to class I think they should be outside of class
=> serializer accept modelName instead of model

blueprints/mirage-serializer/files/__root__/mirage/serializers/__name__.js, blueprints/mirage-serializer/index.js
Because why not :wink: 
FYI, the blueprint defaults to `JsonApiSerializer`.
=> Adds a mirage-serializer blueprint

docs/v0.2.x/installing-and-updating.md
When migrating from `0.1.x` to `0.2.x`, the default folder for Mirage moves from `/app/mirage` to `/mirage`.
Having files in both folders __do__ conflict, I've spent quite some time figuring out why `/mirage/config.js` was not interpreted.
The reason is `/app/mirage/config.js` takes precedence.
The fix is to move everything from `/app/mirage` to `/mirage`.
Maybe a code-based solution should be planned, but a documentation quickfix might help potential users meanwhile.
=> Add docs to migrate from 0.1.x to 0.2.x

addon/route-handler.js, addon/server.js
I think `extractArguments` should be inside user-facing API, because only user will be passing variable length arguments  and in `route-handler` arguments become more explicit, need your opinion
=> moved `extractArguments` to server class

addon/server.js
since `unhandled` and `handled` requests being logged I thought it would be logical to add logging for `passthrough requests` also
=> added `passthroug request` logging

addon/route-handlers/shorthands/base.js, addon/route-handlers/shorthands/delete.js, addon/route-handlers/shorthands/get.js, addon/route-handlers/shorthands/post.js, addon/route-handlers/shorthands/put.js
* moved selecting request handler to constructor
* made more explicit selecting handler
* changed order and removed unnecessary arguments for handler methods
=> shorthands cleanup

addon/route-handlers/shorthands/base.js, addon/route-handlers/shorthands/post.js, addon/route-handlers/shorthands/put.js, addon/serializer-registry.js
In #506, when AMS serializers used registry.normalize, they didn't have a model.modelName property. Now instead of discovering modelName from the payload props, we can pass it down from the shorthands.
=> attempt at #506, passing modelName to registry.normalize for AMS compatibility

docs/v0.2.0-beta.3/factories.md
`faker.list.cycle` returns a function that expects an iteration to be passed: https://github.com/samselikoff/ember-cli-mirage/blob/dfd7f620277e3f9bddf6d817a19fd5802e5aaf33/addon/faker.js#L13
=> Add iteration argument to faker.list.cycle

addon/serializer-registry.js, tests/integration/serializers/base/override-serialize-test.js
http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/serializers/#serializeresponse-request
Sometimes while on the way to the serializer's serialize function, the request argument gets left behind. These changes should make sure it gets there.
=> always pass Serializer.serialize the request as a second argument

addon/serializer-registry.js, tests/integration/serializers/base/associations/sideloading-collection-test.js
Just this one traversal function wasn't checking for null relatedModels.
=> filtering for existence

addon/route-handler.js
This only fixes the case in `RouteHandler#_getMirageResponseForRequest`. I'm not particularly familiar with the architecture of Ember CLI Mirage, so this might not be the ideal fix.
The issue that I encountered was due to my having setup two models with a hasMany/belongsTo association, and then writing fixtures for them which did not specify the IDs required to make that association work.
What ultimately happened was the model property generated by `BelongsTo#addMethodsToModelClass` had [an assert in its `set` function](https://github.com/samselikoff/ember-cli-mirage/blob/b0c7ef511796d1cb44fc18dbbbd2c6e5664cb215/addon/orm/associations/belongs-to.js#L47) which was ultimately throwing a bare JS string.
Eventually that exception unwound until it hit [the catch block in …
=> Always include original message on rethrow errors

docs/v0.2.0-beta.1/defining-routes.md, docs/v0.2.0-beta.1/route-handlers.md, docs/v0.2.0-beta.1/shorthands.md, docs/v0.2.0-beta.2/defining-routes.md, docs/v0.2.0-beta.2/route-handlers.md, docs/v0.2.0-beta.2/shorthands.md, docs/v0.2.0-beta.3/defining-routes.md, docs/v0.2.0-beta.3/route-handlers.md, docs/v0.2.0-beta.3/shorthands.md
Fixed some expressions apparently missing arrows.
I wish we could check the syntax of codes embedded in documents...
=> Add missing arrows

docs/v0.2.0-beta.3/models.md
Documentation for specifying the model name in belongsTo / hasMany associations.
Please let me know if the wording is fine and I'll add it to the other doc versions.
Born out of #537
=> Add belongsTo / hasMany model name documentation

addon/route-handlers/shorthands/base.js, tests/unit/route-handlers/shorthands/base-test.js
This allows using an id value that is passed as part of the submitted json api resource when a value is not specified in the request params.  It also removes integer parsing of ids per #462.  I've tried to add a test as well although I'm having a hard time running the tests locally to verify :(
=> Fixes #548: Use json api id when available.

bower.json, package.json
Starting with ember-cli 2.3.0-beta.2 these two dependencies move from bower to npm.
=> Updating ember-cli and related deps

index.js
The check in #543 is correct, but if a project has "in-repo-addons" then
it will include `ember-addon` in `package.json` without it being an
addon.
The following shows how in-repo-addons are discovered https://github.com/ember-cli/ember-cli/blob/282641ba662292afb40cb88cdf31557a3e4cc6b7/lib/models/addon-discovery.js#L160
Without this #524 still happens if you have in-repo-addons..
cc @cibernox
=> Fix the fix on addon integration.

docs/v0.2.0-beta.1/models.md, docs/v0.2.0-beta.2/models.md
The paragraph from #545 pertains to older betas as well I think.
=> Retrofit belongsTo / hasMany model name docs to older betas

addon/server.js, config/environment.js, tests/unit/server-test.js
This PR adds a `defaultPassthroughs` array to `server.js`, and automatically configures passthroughs for all URLs in the array when `ENV['ember-cli-mirage'].useDefaultPassthroughs` is true (defaults to true).
For more, see #552 & [the related blog post](http://blog.isleofcode.com/configuring-ember-cli-mirage-and-pretender-for-production/)
=> Add default passthroughs; fix #552

index.js
I only need Mirage for acceptance test, but it is included in 'development' environment as well. This PR changes the logic for determining when to include Mirage. It preserves the previous behavior where Mirage is included by default in all non-production environments and it can be enabled for 'production' environment. It adds ability to explicitly disable Mirage in other environments. It probably doesn't make any sense for disabling in 'testing', but it make sense to disable it for 'development' if the API server is fully implemented and there is no need for mocking.
=> Allow Mirage to be disabled for non-production environments

addon/route-handlers/shorthands/base.js, tests/unit/route-handlers/shorthands/base-test.js
typeof can produce inconsistent behavior here since typeof `[]` and
`null` is 'object'.
We still want to pass `null` as the id since that is valid when for
example removing the link to the other object.
=> Fix check for belongsTo relationship and use null data.

docs/v0.2.0-beta.5/serializers.md
The example is updated but the surrounding text still says "relationships" rather than "include"
=> Update serializers documentation for "include" rather than "relationships"

addon/index.js, addon/orm/associations/association.js, addon/orm/associations/has-many.js, tests/integration/schema/has-many/accessor-test.js, tests/integration/schema/has-many/create-association-test.js, tests/integration/schema/has-many/has-many-helper.js, tests/integration/schema/has-many/new-association-test.js, tests/integration/schema/has-many/set-association-ids-test.js, tests/integration/schema/has-many/set-association-test.js
This adds an optional `inverseOf` option on `hasMany` associations so that you can correctly map relationships in which the child model has a non-default association key.
I also expanded test scenario coverage of all the tests that use the HasManyHelper so that they also include every permutation of default and non-default keys for the hasMany association and its inverse.
Note that I fixed what I would consider to be a bug, which is that the `newFoo` and `createFoo` methods were being named based on the destination model name and not the local key. That makes multiple associations to the same model type impossible to use unambiguously.
=> Inverse Foreign Keys

index.js
This fix allow nesting ember-cli-mirage as an addon dependency of another addon.  
As described on the ember-cli docs here:
http://ember-cli.com/extending/#addons-depending-on-other-addons
The implementation has been discussed at length here:
https://github.com/ember-cli/ember-cli/issues/3718
=> Allow for nesting ember-cli-mirage addon in another addon

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/included-test.js
Recently started using ember-cli-mirage. Was very happy when I found out it already supported the `include` query param for the JSON::API adapter!
However, per the JSON::API spec, when a dot-path relationship is included, all intermediate relationships should be included as well (see the second text box of the [Inclusion of Related Resources](http://jsonapi.org/format/#fetching-includes) section). This PR should make mirage comply with that.
=> Include intermediate dot-path relationships

addon/factory.js, addon/utils/reference-sort.js, tests/unit/factory-test.js, tests/unit/reference-sort-test.js
This PR lets you reference dynamic attributes from different dynamic attributes.
Currently you are able to reference static attributes from dynamic ones like so:
```js
// mirage/factories/user.js
import Mirage from 'ember-cli-mirage';
export default Mirage.Factory.extend({
age: 18,
is_admin: function(i) {
return this.age > 30;
}
});
```
but I also want to be able to reference dynamic attributes from dynamic attributes like so:
```js
// mirage/factories/user.js
import Mirage from 'ember-cli-mirage';
export default Mirage.Factory.extend({
year_of_birth() {
return faker.random.number({ min: 1900, max: 2000 });
},
year_of_death() {
return faker.random.number({ min: this.year_of_birth, max: this.year_of_birth + 90 });
}
});
```
That is now possible. I also made sure it does not matter in what …
=> [Feature] reference dynamic attributes from dynamic attributes.

app/initializers/ember-cli-mirage.js, tests/acceptance/manually-starting-test.js
Even though this was partially resolved in https://github.com/samselikoff/ember-cli-mirage/issues/183, I had a situation where I only wanted to start Mirage in specific tests as it was being introduced to a project.
Let me know what you think:
* Is there a better place to put `startMirage` rather than in the initializer file?
* Is `startMirage` a good name?
* Any other testing approaches?
Once this is resolved I'd be happy to update the cookbook documentation as well.
=> Extract startMirage from initializer

addon/route-handlers/shorthands/base.js, tests/unit/route-handlers/shorthands/base-test.js
Previously, this method assumed that the request body contained an `attributes` property which is fine when you are actually updating properties of a model (e.g. changing the name of a user or the content of a post).
My changes allow updating model relationships without modifying the existing models (e.g. changing a post's author to another user).
=> refactoring getAttrsForRequest to allow relationship updates

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/links-test.js
This is helpful for async relationships that are driven by links in the
response, instead of relationship IDs.
JSONAPI Links spec: http://jsonapi.org/format/#document-links
Usage:
```es6
import ApplicationSerializer from './application';
export default ApplicationSerializer.extend({
links: {
comments: {
related: function(model) { return `/api/comments?post_id=${model.id}`; },
self: function(model) { return `/api/posts/${model.id}/comments`; }
}
});
```
=> Add optional links to JSONAPI response

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/links-test.js
The `link` serializer function was incorrectly firing every iteration of
the relationships, which caused the last link to be assigned for
everything. We now get the link data once before relationships are
processed, and refer to it when iterating.
Refactored the test to process multiple relationships to ensure this
doesn't happen again.
=> Ensure links work with multiple relationships

docs/v0.2.0-beta.7/models.md
The `isNew()` instance method for the `mirage-model` is supposed to return true only when the model hasn't been persisted yet to the mirage db.
Added the word `not` :)
=> Corrects the meaning for the definition of `isNew()`

addon/server.js
On master was seeing this in the output:
```
Successful request: GET $[request.url}
```
Subtle typo causing this problem.
=> Fix typo in handledRequest string interp.

addon/db-collection.js
For issue #658 
I noticed that for `firstOrCreate` the documentation lists the second param as `attributesForCreate` while the code uses `attributesForNew`. Do you have a preference as to which should be referenced in the YUIDoc comments?
Also wasn't sure if I should document the `IdentityManager` methods at all. I didn't on this pass, but if I should, just let me know!
=> adds YUIDoc comments to addon/db-collection

README.md, package.json
To address #669 
* Changed the description in package.json
* Update the README
In the readme I think "fixtures" is a little better. I often seen people
turn to stubbing with fixtures first when trying to test against an API.
Using "mocks" outside of a testing context doesn't make sense.
=> Remove the term mock on the master branch

_config.yml, about/index.html, docs/v0.2.0-beta.7/acceptance-testing.md, docs/v0.2.0-beta.7/defining-routes.md, docs/v0.2.0-beta.7/index.md, docs/v0.2.0-beta.7/quickstart.md, docs/v0.2.0-beta.7/route-handlers.md, docs/v0.2.0-beta.7/seeding-your-database.md, docs/v0.2.0-beta.7/serializers.md, docs/v0.2.0-beta.7/upgrading.md, index.html
To address #669 on the gh-pages branch.
I audited the gh-pages brach for use of the word "mock". This is not a simple find/replace and needs some review before merging.
For the docs, I only changed the v0.2.0-beta.7 version.
Beyond my own pedantic hangups about terminology, I think this is a nice improvement. The work "mock" was used generally to mean:
* noun - "a mock" - a route handler
* noun - "a mock" - data returned from a route handler or stub data
* verb - "mock" or "mock out" - simulate a real API or implement a route handler
* adjective - "mock server" - fake server
Instead I replaced these uses with "fake", "simulate", "data", "stub", "route handlers", "Mirage" or anything else that seemed to convey the original intent.
=> Remove "mock" references in documentation

config/environment.js
The current `usingProxy` implementation only accounts for the long form of the `--proxy` flag. Added checks for `-pr` and `-pxy` aliases.
=> support aliases for --proxy flag (-pr, -pxy)

blueprints/ember-cli-mirage/index.js
This is a follow-up to #694. 
The version of `Faker` that clients will consume is controlled by `addBowerPackagesToProject` in the default blueprint's `afterInstall` hook. I was missing some of the supercool randomization functions that @bgentry was alluding to until I made the change there.
=> Update faker version specified in afterInstall hook

docs/v0.2.0-beta.9/serializers.md
Fix the incorrect capitalization of the imported `JSONAPISerializer` which causes ReferenceError in run-time.
=> Fix a capitalization typo for `JSONAPISerializer`

addon/route-handlers/base.js
links to a dead page.
should http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#normalizejson redirect to http://www.ember-cli-mirage.com/docs/v0.2.0-beta.9/serializers/#normalizejson instead of hardcoding it?
=> update error url

addon/route-handlers/base.js, blueprints/ember-cli-mirage/files/__root__/config.js
after 0.2.0 final dropped, I found some links in blueprint and in route-handler which links to 0.2.0.beta versions.
=> update links to v0.2.x docs

docs/v0.2.x/serializers.md
This will close #659.
Let me know if we should say anything about a comma separated list of relationships paths or dot-serperated relationships paths.
=> Document usage of `?include` query param

addon/serializer.js, tests/integration/serializers/active-model-serializer-test.js
I was trying to serialize a model that has a multiple hasMany() relationships with the standard ActiveModelSerializer plus `include` of these relationships with `embed: true`.
Although the regular fields are serialized fine as `underscore`, the embedded relationship keys were still in camelcase.
As it turned out, `camelize` was still hard-coded instead of `keyForRelationship`, so I fixed it and added a test. All existing tests still pass.
=> Fix serializing embedded collection keys

_sass/_base.scss
@samselikoff I think this is the best course of action. By adjusting the styles we don't need to open code fences in markdown with the `text` type and we still get to keep _some_ highlighting for those blocks. The downside is that if a code block does have real errors we rely on only a keen eye.
=> Remove styles for highlighting syntax errors

docs/v0.2.x/route-handlers.md
The arrow function can’t be used when calling `this.serialize` because `this` won’t be the route.
=> Fix example usage of route’s this.serialize

docs/v0.2.x/factories.md, docs/v0.2.x/models.md
The non-relationship-building example is a bit contrived, but the best I could come up with off the top of my head. Fixes #766.
=> [DOC] Add documentation for afterCreate() hook

docs/v0.2.x/serializers.md
You mentioned this to me at Wicked Good Ember but it’s not documented. This example is maybe not the best, I can update it if you have a better suggestion.
Also, I threw in a commit to fix what looks to me to be a typo. If you’d prefer that to be in a separate PR, let me know.
I think this won’t help with my situation, which involves serialising a related model that [may or may not be present](https://github.com/travis-ci/travis-web/blob/a11090ad28459b3b01b409579dc6e9d366263352/mirage/serializers/build.js):
```
serialize(object, request) {
const response = object.attrs;
if (object.commit) {
response.commit = this.serializerFor('commit').serialize(object.commit, request);
}
return response;
}
```
I’d ideally be able to use `includes: ['commit']` and ignore it if there’s no related commit, …
=> Include function documentation

addon/db-collection.js, addon/db.js, addon/orm/schema.js, tests/unit/db-test.js
Hey Sam,
I want to add a finder method that takes a multiple attribute query (like `where`), but always returns 0 or 1 results (like `find`).
This method does exactly that.
My particular use case was for finding by slug instead of id in route handlers, like so:
````
let slug = request.params.id;
return schema.contacts.findBy({ slug: slug });
````
Please let me know if this is acceptable, and I'll write the docs for the site.
=> Add findBy(query) method to db / schema

blueprints/ember-cli-mirage/index.js, bower.json, index.js, package.json, tests/unit/import-files-test-node.js
I'm on a quest to remove Bower dependencies from our apps and addons where possible in the ultimate hope that once [Ember itself moves to npm](https://github.com/ember-cli/ember-cli/issues/4546) we'll be able stop using Bower entirely.
This changes switches over Faker, Pretender and friends over to come from npm, and eliminates the installation of those two packages via Bower in the default blueprint.
=> Pull third-party dependencies from npm instead of Bower

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/included-test.js, tests/integration/serializers/json-api-serializer/associations/model-test.js
Looks like the tests were setup sufficiently to cover this. Did modify a couple tests to reflect the new behavior.
Closes #821
=> JSONAPIAdapter shorthand routes need to include empty relationship values by default

docs/v0.2.x/quickstart.md
=> Remove unneeded argument

docs/v0.2.x/quickstart.md
A few changes to the readme file for clarity and consistency.
- Added a semicolon on line 13
- The `author.js` model that gets generated has `Model.extend({})` instead of just `Model`
- Labeled the route handler for reference for clarity on line 61
=> Update README.md for clarity

addon/server.js, tests/integration/server-config-test.js
If / is passed as the namespace it shouldn't end up as //
This is my attempt at a workaround for #826 it allows me to send `/` as my namespace and then tests work again.  I don't necessarily understand what all of these options do and what the default behavior should be, so please don't hesitate to tell me this is a mess.
=> Allow a namespace of / to be used

addon/server.js, tests/dummy/app/app.js, tests/integration/http-verbs-test.js, tests/integration/server/resource-shorthand-test.js
Shorthands are super useful, but for very generic CRUD it might be a bit tedious to define a route handler for every endpoint, so I thought that Rails-like `resource` helper would help with that.
=> add :resource helper for handling generic CRUD

addon/orm/collection.js, tests/integration/orm/collection-test.js
`sort` returns a new collection with models sorted according to the function as an argument to the method.
@samselikoff Should docs be in a separate commit?
=> Add `sort` to orm/collection

addon/orm/associations/belongs-to.js
Not a big thing, but I think it looks more expressive this way besides being DRY.
=> reuse getForeignKey in getForeignKeyArray method in BelongsTo class

README.md
Apparently the link was not updated at some point.
=> fix link to contributing guidelines

docs/v0.2.x/shorthands.md
I've stumbled at using this.resource, as it was not clarified what version it was added to mirage (still using 0.2.1)
=> Update version of resource helper to 0.2.2

addon/route-handler.js, addon/server.js, package.json, tests/integration/route-handlers/function-handler-test.js
This enables users to work with promises in route function handlers, e.g.:
```js
this.get('/users', () => {
return new Promise(resolve => {
resolve(new Response(200, { 'Content-Type': 'text/csv' }, 'firstname,lastname\nbob,dylan'));
});
});
```
=> Add support for promises in route functions

docs/v0.2.x/manually-starting-mirage.md
Updating old documentation.  I'm not sure why the original docs advised running the initializer method; the startMirage function should work just fine—no helper file should be necessary.
Closes #915 (not automatically, though)
=> [DOCS] Advise user to shutdown pretender servers

package.json
This PR addresses concerns from #863 around a lack of flexibility around which version of faker is used.  This PR lets the range float from 3.0.0 so by default users will get the latest version, but if they want to use a specific version they can specify that version in their own package.json.
I tested this out a few ways:
* No Faker version in my app's package.json, I get Faker 3.1.0
* Faker 3.0.1 in my app's package.json, I get Faker 3.0.1
* Faker ^3.0.0 in my app's package.json, I get Faker 3.1.0
=> Let faker float from 3.0.0

package.json, tests/acceptance/manually-starting-test.js, tests/dummy/app/adapters/word-smith.js, tests/dummy/app/app.js, tests/dummy/app/controllers/application.js, tests/dummy/app/models/address.js, tests/dummy/app/models/blog-post.js, tests/dummy/app/models/contact.js, tests/dummy/app/models/friend.js, tests/dummy/app/models/pet.js, tests/dummy/app/models/word-smith.js, tests/dummy/app/router.js, tests/dummy/app/routes/application.js, tests/dummy/app/routes/close-friends.js, tests/dummy/app/routes/contacts.js, tests/dummy/app/routes/friends.js, tests/dummy/app/routes/pets.js, tests/dummy/app/serializers/blog-post.js, tests/dummy/app/serializers/word-smith.js, tests/helpers/destroy-app.js, tests/helpers/start-app.js
Upgrade is required when using the newest JSCS linter/executable.
ember-sauve 4.0 uses the 3.0 JSCS linter instead of the 2.x. with defaults the “esnext” and “verbose” option. This will continuously show an error in atom which this update fixes.
=> Upgrade to ember-suave 4.0

addon/utils/read-modules.js
This removes the letter "i" from the message. It appears to be a typo that snuck in. (A previous version of this file doesn't have the i: https://github.com/samselikoff/ember-cli-mirage/blob/f95aa53262164953f70c970812d8462aa13feab2/addon/utils/read-modules.js#L32).
=> Typo fix: Remove errant "i" from subdirectory msg

addon/orm/collection.js, tests/integration/orm/collection-test.js
Adds slice method to collections. If someone else gets to a solution for proxying enumerable methods to Array and lodash first, great. But this would be helpful too.
=> Add slice method to collections

package.json, tests/integration/serializers/base/full-request-test.js
See https://github.com/tildeio/route-recognizer/pull/91
Right now if id contains a special character like ```/``` or ```:``` then we need to use a workaround like:
```
this.get('/posts/:id', (request, schema) {
let decodedId = decodeURIComponent(request.params.id);
return schema.posts.find(decodedId);
});
```
=> Upgrade route-recognizer to decode dyanmic path segments

addon/association.js, addon/index.js, addon/orm/model.js, addon/orm/schema.js, addon/server.js, addon/utils/is-association.js, tests/integration/factories/helpers-test.js, tests/unit/model-test.js, tests/unit/schema-test.js, tests/unit/server-test.js
Another feature I was happy to see in the roadmap as it's super useful :). Works with name override, traits and attribute overrrides.
I think traits / association handling may need some refactoring, the responsibilites are a bit split betweem the factory itself and the server and it's not really clear what should happen where (e.g. some attributes are deleted in factory, others in server). And the building / creating could be actually delegated to some other object so that there's no so much logic directly in the server. But that's probably out of the scope of this PR.
=> implement association helper

docs/v0.2.x/configuration.md
=> fix(config-docs): document requirement to define namespace in cordova/electron envs

addon/route-handlers/base.js, addon/route-handlers/function.js, tests/integration/server/custom-function-handler-test.js
Adds a helper method to parse a request sent using `formData`. Currently just supports simple key/value url encoded strings, does not support `multipart/form-data`.
Related to https://github.com/samselikoff/ember-cli-mirage/issues/753
=> adds helper method to normalize form data requests

docs/v0.2.x/manually-starting-mirage.md
This bit me on a recent project. `import 'yourapp/initializers/ember-cli-mirage'` is not a valid path inside an ember addon. Needs to be:
```js
import { startMirage } from 'dummy/initializers/ember-cli-mirage';
```
=> include note about import path in an Ember addon

docs/v0.2.x/factories.md
Just a missing space in one of the code examples.
=> Missing space

docs/v0.2.x/factories.md
Clarified what are the use cases for `afterCreate` and `association`, it wasn't really obvious that `association` can't handle `hasMany` relationships.
=> clarify 'association' and 'afterCreate' use cases

index.js
https://github.com/samselikoff/ember-cli-mirage/issues/986
=> Added falsy condition to exclude faker.js & pretender.js in production build.

CHANGELOG.md, addon/db-collection.js, addon/factory.js, addon/orm/associations/belongs-to.js, addon/orm/associations/has-many.js, addon/orm/collection.js, addon/orm/schema.js, addon/serializer-registry.js, addon/serializer.js, addon/serializers/json-api-serializer.js, addon/server.js, addon/utils/extend.js, addon/utils/is-association.js, addon/utils/read-modules.js, addon/utils/reference-sort.js, app/initializers/ember-cli-mirage.js, package.json, tests/integration/route-handlers/function-handler-test.js, tests/integration/serializers/base/basic-test.js
adapted:
- load patterns (lodash4 uses `lodash/function` instead of `lodash/category/function`
- `uniq` to `uniqBy` using shorthands.
- `map` does not have a context anymore, changed for a 2 step sort + mapped insertion
- `invoke` to `invokeMap` when applied to a collection
=> feat(Lodash): adapting to use lodash 4 using latest ember-lodash

docs/v0.2.x/models.md
TIL mirage has `findBy`, and I can stop writing `users.where({ username }).models[0]` 😜
=> Add documentation for findBy

addon/orm/schema.js
Fixes https://github.com/samselikoff/ember-cli-mirage/issues/979
`Object.assign` is not supported by PhantomJS, which is the default test runner for ember apps. This replaces usage of `Object.assign` with [Lodash's assign](https://lodash.com/docs/4.17.4#assign).
LMK if this isn't the correct target branch.
=> Use lodash assign

addon/server.js
Number.isInteger is not well supported in older browser environments so we should use lodash isInteger method instead. Specifically, my CI tests in phantomjs were failing because of this.
=> Replace Number.isInteger with lodash isInteger

addon/server.js, tests/unit/server-test.js
`_mapAssociationsFromAttributes` method modifies factory's attrs field.
Example:
*Before* this method callled attrs can be `{ author: { ..association } }`.
*After* this method called attrs will be `{ authorId: 1 }`
So association will be generated only first time.
As a fix I copy the original factory to apply associations.
FIx for #1021
=> fix factory association feature

docs/v0.2.x/factories.md
Display which versions to expect support for referencing other attributes from within dynamic attributes.
Otherwise the docs can be misleading because the feature is half-implemented (the attributes are there but always return `undefined` because the getter is only half implemented) prior to 2.4.
=> Add a note about dynamic attribute support

blueprints/ember-cli-mirage/index.js
I ran into this issue when writing unit tests for an initializer.
=> Fixes generated code for destroy app helper

addon/utils/read-modules.js
While testing babel@6 upgrades with apps and addons, there are issues when relying on the global require.
In this case, we are just trying to dynamically grab something from the loader so we can use this `import require from 'require';`.
=> Import `require` to avoid issue in babel@6.

addon/server.js, tests/integration/server/get-full-path-test.js
Fixes issue #901. 
Adds tests to reproduce issues brought up in issue #901 and makes them pass. These test for 4 conditions for different namespace and urlPrefix inputs
1. with a leading slash
2. without a leading slash
3. with a trailing slash
4. as empty strings
Any feedback is welcome.
=> Make host/namespace support more robust

docs/v0.2.x/database.md
Seems like [findBy](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/db-collection.js#L97) exists on db collections, but is not documented on [the site](http://www.ember-cli-mirage.com/docs/v0.2.x/database/#find)
=> Documentation for findBy

addon/server.js, tests/integration/server/resource-shorthand-test.js
This adds in the ability to specify a customized path in the resource helper.
Currently with a `server.get()` shorthand, the second parameter can be a string for the collection name, if it doesn't match the given path. This PR will bring the `server.resource()` helper in line with that customizability, although it places this option inside the second parameter's option hash as `path`.
```js
// given "blog-posts" resource name and a custom path:
server.resource('blog-posts', { path: '/posts' });
// returns shorthands:
server.get('/posts', 'blog-posts');
server.get('/posts/:id', 'blog-posts');
server.post('/posts', 'blog-posts');
server.put('/posts/:id', 'blog-posts');
server.patch('/posts/:id', 'blog-posts');
server.delete('/posts/:id', 'blog-posts');
```
You could also specify an absolute …
=> Add Resource helper custom path parameter

docs/v0.3.x/shorthands.md
Docs for resource helper path update from https://github.com/samselikoff/ember-cli-mirage/pull/1068
=> [DOCS] Update Resource helper docs

README.md
Noticed docs link was pointing to old version. Couldn't find a link that auto-redirected to latest.
=> Updating docs link

blueprints/ember-cli-mirage/index.js
Hey folks,
Great addon. Thanks for all the hard work.
ESLint has been preferred over JSHint. https://github.com/ember-cli/ember-cli/pull/6526
I adapted the `afterInstall` hook to change `.eslintrc` and `tests/.eslintrc`. 
It also changes JSHint files if they exists, for ember-cli < 2.12.
Cheers!
=> Add server as a global for ESLint in afterInstall

docs/v0.3.x/quickstart.md
hi 👋 
I am getting a new project started with Mirage and I noticed the quickstart guide didn't mention that Faker.js was included but was requiring it in the factory files. I did a bit of hunting in the guides and found it [here](http://www.ember-cli-mirage.com/docs/v0.3.x/seeding-your-database/), so I went ahead and added it to the quickstart guide for clarity.
Hopefully it saves someone else a few minutes of hunting to determine if Faker.js is included 😄
=> note that Faker.js is included with mirage

addon/route-handlers/base.js, tests/unit/route-handlers/shorthands/base-test.js
This commit updates `_getRequestAttrs` to normalize any `hasMany`
relationships in a request's JSON data.
By default, Ember Data will serialize `hasMany` relationships if they
are many-to-none, many-to-many, or if serialization is forced via
`serialize: true` in the `attrs` property on [DS.JSONSerializer](https://emberjs.com/api/data/classes/DS.JSONSerializer.html).
(One-to-many are not serialized by default).
Before this commit, Mirage only normalized attributes and `belongsTo`
relationships. Because `hasMany` relationships weren't normalized, many-
to-many relationships weren't saved via the shorthand route handlers or
any custom route handlers that used `this.normalizedRequestAttrs()`
(which calls `_getRequestAttrs`).
For example, assume a many-to-many relationship between `Authors` …
=> Normalize hasMany relationships

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/links-test.js
JSON API spec says that a `relationships` object must contain at least one of the props, but it could contain all of them. So, `links` are able to be with `data` as well.
Link to the article of the spec: http://jsonapi.org/format/#document-resource-object-relationships
An article about relationships when they are defined, but empty: http://jsonapi.org/format/#document-resource-object-linkage (like a case in tests)
fixes #973
=> Fixed existence of `relationships.data` if `links` are defined

package.json
This package is unused in ember-cli-mirage (and it has been deprecated upstream).
=> Remove broccoli-unwatched-tree dependency.

ember-cli-build.js
This satisfies the following deprecation warning:
```
DEPRECATION: Putting the "includePolyfill" option in "babel" is deprecated, please put it in "ember-cli-babel" instead.
```
=> Replace "babel" -> "ember-cli-babel" when specifying `includePolyfill`

package.json
This makes CI pass again since it includes https://github.com/emberjs/data/pull/4743 which fixes the broken `_lookupFactory()` call in Ember Data.
/cc @samselikoff
=> Update "ember-data" to v2.11.3

package.json
We are already using stuff like `let` and `const` in `index.js` so having `engines` allow Node 0.12 has been a lie 😉
=> package.json: Update "engines" property

package.json, yarn.lock
`ember-get-config` issued a noisy warning when used with engines in `0.2.1`, and it's locked to that version here.
=> Unlock and upgrade ember-get-config

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/collection-test.js, tests/integration/serializers/json-api-serializer/associations/includes-test.js, tests/integration/serializers/json-api-serializer/associations/key-for-relationship-test.js, tests/integration/serializers/json-api-serializer/associations/links-test.js, tests/integration/serializers/json-api-serializer/associations/model-test.js, tests/integration/serializers/json-api-serializer/associations/polymorphic-test.js
Add alwaysIncludeLinkageData option to JSONAPISerializer, default to
false. By default, linkage data will be present for included resources.
=> [fixes #1146] Change default JSONAPI data linkage behavior

app/initializers/ember-cli-mirage.js
proper solution is to just reexport stuff in the `app` folder and have the real code in the `addon` folder, but reverting that part should be enough for now.
=> Revert "New Module Imports" in "app" folder

addon/orm/model.js
Fixes #1061 and a loading delay when using this in development which causes the browser to hang.
=> Only _definePlainAttribute if not an association

docs/v0.3.x/installation.md
As far as I'm aware, bower isn't required to run this addon anymore.
=> Remove mention of bower in install guide

addon/server.js, tests/integration/factories/helpers-test.js
#1076 This will fix the `Model not registered` when including the `association` in a dasherized factory/model name (i.e. `blog-post`).  I have added a breaking test in the first commit and followed it up with the commit to fix it.
This is a duplicate PR building off of the one started in [1101](https://github.com/samselikoff/ember-cli-mirage/pull/1101).
Thanks!
=> Camelize model type to fix `association` helper in dasherized factories

docs/v0.3.x/serializers.md
This PR updates the docs to use the same serializer name  `ApplicationSerializer` as the blueprint.
=> for consistency switch base serializer to application serializer

addon/utils/extend.js
The extend mechanism, which we inherited from Ember pre-dates the advent of native ES class syntax. Among other things, this meant manually constructing the prototype chain when expressing the inheritance.
This change lets the `class` syntax do the heavy lifting of prototype wiring while making the code more clear as to its intent.
As a bonus, instances created with this class show up in development tools as `class Child` instead of
```js
function () {
return parent.apply(this, arguments);
}
```
Still not ideal, but better than the alternative.
Finally, the `__super__` property was removed since it's of dubious value and did not cause any tests to fail.
=> Base Class.extend() on native es class syntax

addon/orm/schema.js, addon/route-handlers/base.js, addon/server.js
This is just cosmetic. Though the docs are largely unchanged, users could navigate to the link thinking they're looking at 0.3.x docs when it's 0.2.x.
Apologies if there was another PR addressing this. I didn't see it if when I tried searching for it.
=> update error message for 3.x version

tests/integration/server/resource-shorthand-test.js
We were testing custom path behaviour in every test here. I've moved the tests for custom path behaviour into one test. The third part of #1206.
=> refactor: move custom path behaviour into one test

tests/integration/http-verbs-test.js, tests/integration/route-handlers/function-handler-test.js, tests/integration/serializers/base/full-request-test.js, tests/integration/server/custom-function-handler-test.js, tests/integration/server/customized-normalize-method-test.js, tests/integration/server/resource-shorthand-test.js, tests/integration/server/shorthand-sanity-test.js
=> refactor: use async/await in tests

package.json, yarn.lock
Upgrades to 1.6.1 as we should see improvements in memory leaks from pretender. Helps merge #1217
=> chore(pretender): upgrade to 1.6.1

addon/server.js, app/initializers/ember-cli-mirage.js, tests/integration/server-config-test.js
Track requests with Pretender in test mode [#1200](https://github.com/samselikoff/ember-cli-mirage/issues/1200)
Our app depends on pretender tracking for assertions in our tests about outgoing requests. It would be great if this were configurable.
=> make pretender request tracking configurable

addon/orm/associations/belongs-to.js, addon/orm/model.js, addon/orm/schema.js, tests/integration/orm/belongs-to/2-named/association-create-test.js, tests/integration/orm/has-many/regressions/many-to-many-inverse-set-bug.js
Saving a graph of relationships was triggering multiple saves on the same object which was leading to some bugs. I added a simple `isSaving` dictionary to the Schema object to keep track of which models were already being saved during a cascading save, to avoid this.
=> [closes #1240] Fix many-to-many set bug

addon/route-handlers/shorthands/get.js, addon/serializer-registry.js, addon/serializer.js, addon/serializers/active-model-serializer.js, addon/serializers/json-api-serializer.js, addon/serializers/rest-serializer.js, tests/integration/route-handlers/get-shorthand-test.js, tests/unit/serializers/active-model-serializer-test.js, tests/unit/serializers/json-api-serializer-test.js, tests/unit/serializers/rest-serializer-test.js
Introduces a new `getCoalescedIds` method for serializers, to encapsulate knowledge on how to deserialize coalesced Ids from the given request in that layer, so we can support the proper way for each serializer independently.
Fixes #1202 
cc @cibernox
=> Support coalesce option properly according to JSON:API spec

addon/server.js, tests/integration/http-verbs-test.js
Hi guys!
Good job with this plugin, we at Uniplaces use it in all our projects and it makes the development super easy, it is completely essential now!
This adds the possibility to mock `option` requests. I followed what you guys said here (https://github.com/samselikoff/ember-cli-mirage/issues/804). Hope it is alright!
- I've renamed the internal `options` (configuration options) as it is limiting us (we couldn't define the `options` method). I would love to hear from you guys if you think this can break APIs. 
- From my understanding, we shouldn't be changing options from outside of the server and I obviously renamed the inside calls to `this.options` solving the above problem. 
If it does break, it would be cool to discuss a better way of doing this :) (and create tests to confirm …
=> Add options verb mocking

addon/serializer.js, tests/integration/serializers/base/associations/sideloading-collection-test.js, tests/integration/serializers/base/associations/sideloading-model-test.js
Consider the following models, and note the serialization method:
```
// User (serializer sideloads posts)
export default Model.extend({
posts: hasMany('post')
});
// Post (serializer embeds comments)
export default Model.extend({
authors: hasMany('user')
comments: hasMany('comments')
});
// Comment
export default Model.extend({
post: belongsTo('post')
});
```
Assuming we have populated our database and we serialize a user, the
resulting serialization may look like this:
```
{
user: {
id: '1',
name: 'John',
postIds: ['1', '2']
},
posts: [
{ id: '1', title: 'Lorem', comments: [{ id: '1', text: 'first' }] },
{ id: '2', title: 'Ipsum', comments: [] }
]
}
```
Currently, there is a bug in Mirage which causes an error to be thrown
when attempting this kind of serialization:
`TypeError: Cannot …
=> Fix serialization of sideloaded associations with embedded associations

app/initializers/ember-cli-mirage.js
I didn't mean to change this, and it breaks apps that have initializers that reference this one in their `before` or `after` fields.
=> Revert initializer name

addon/orm/model.js, tests/integration/orm/schema-verification/mixed-test.js
While this solution works I don't really know enough about the mirage internals to know if it is the right fix. 
Hopefully a test is worth a thousands words here, I'm finding this issue difficult to explain. This should be supported:
```
user: Model.extend({
authoredPosts: hasMany('post', { inverse: 'authors' }),
authoredBooks: hasMany('book', { inverse: 'authors' })
}),
post: Model.extend({
authors: hasMany('user', { inverse: 'authoredPosts' })
}),
book: Model.extend({
authors: hasMany('user', { inverse: 'authoredBooks' })
})
```
The `user` model here inverses two other models with the same property.
=> Allow for the same inverse association key to exists many times

addon/serializers/active-model-serializer.js, tests/unit/serializers/active-model-serializer-test.js, tests/unit/serializers/rest-serializer-test.js
Fixes #972 mainly with code I stole from @jelhan 
Changes the `normalize` method in `ActiveModelSerializer` to respect a `normalizeIds` property and convert REST type id arrays into JSONApi objects.
It isn't clear to me that we need a boolean to control this behavior as I don't know of any REST or ActiveModel APIs that *don't* expect data in this format. Hiding this behavior behind a flag does make this a non-breaking change though which is easier to manager.
Edit 6/30: Issues below are solved, leaving them in for posterity.
Some specific issues:
1) Should this transform be applied to ActiveModel type APIs. I think they are similar to REST in this way, but need to confirm with someone who knows.
2) ~Is piggybacking on `serializeIds` the right path here or should I add a new `normalizeIds` …
=> Normalize relationship ids when normalizeIds is set to true

addon/server.js, tests/unit/server-test.js
This will enable you to do:
```js
this.post('token-auth', () => ({ 'jwt': 'xxx' }))._name = 'post:token-auth';
```
```js
export function errorOnAuth() {
let original = server.pretender.handlers.find(h => h._name === 'post:token-auth');
server.post('token-auth', { errors: [{ detail: 'There was an error' }] }, 500);
return function reset() {
server.post('token-auth', original);
};
}
```
unless there is already a way to do this?
=> return pretender handler

addon/orm/model.js, tests/integration/orm/belongs-to/regressions/pr-1312-test.js
Error manifested as:
```
TypeError: Cannot read property 'replace' of undefined
at Cache.func (http://0.0.0.0:62594/assets/vendor.js:64068:16)
at Cache.get (http://0.0.0.0:62594/assets/vendor.js:47407:37)
at decamelize (http://0.0.0.0:62594/assets/vendor.js:64111:29)
at Cache.func (http://0.0.0.0:62594/assets/vendor.js:64016:12)
at Cache.get (http://0.0.0.0:62594/assets/vendor.js:47407:37)
at dasherize (http://0.0.0.0:62594/assets/vendor.js:64115:35)
at toCollectionName (http://0.0.0.0:62594/assets/vendor.js:193841:46)
at toInternalCollectionName (http://0.0.0.0:62594/assets/vendor.js:193846:16)
at Child._validateForeignKeyExistsInDatabase (http://0.0.0.0:62594/assets/vendor.js:190721:78)
at Child.<anonymous> (http://0.0.0.0:62594/assets/vendor.js:190675:16)
```
=> Fix bug setting ID of inverse polymorphic belongsTo relationship

docs/v0.4.x/manually-starting-mirage.md
Following my question on Slack, this PR comes with small changes in the documentation on how **and when** to start Mirage manually.
The added documentation could have been much extended, but I'm waiting to hear your feedback on the necessity to expand further.
=> Reword manual Mirage, with short notes on endpoint config

addon/server.js, tests/unit/server-test.js
This addresses #1298. Hope this change works for you.
=> Don't create extra models in the db when passing association overrides to `create`

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/includes-test.js
This prevents downstream errors when a property of the model is being
passed around that Mirage thinks is an association but is in reality a
primitive (such as a string) property of the model.
Fixes #1327
=> Throw when `include`ing a value that doesn't match an associationKey

addon/serializers/json-api-serializer.js, tests/integration/server/regressions/1322-relationship-path-normalization-test.js
I believe this fixes #1322. This PR adds a commit for the failing test and a separate commit to fix it.
I added the test to the `integration/server/regressions` directory because that seemed the best place for it, but I'm not sure if it really is a regression per se. I'd be happy to move it somewhere more appropriate.
=> Relationship path normalization

addon/route-handlers/base.js, tests/unit/route-handlers/shorthands/base-test.js
Right now, when you provide a path like `/assets/:objectId` and use `this.normalizedRequestAttrs()` in the route handler, it is doing naïve matching on `:id` to break out of the reverse path iterator when looking for the name to "classify" for the model. 
There is no restriction that I am aware of that says route path variables should be `:id`. This change will allow for named route path variables other than :id when using a path and handler that utilizes `BaseRouteHandler#getModelClassFromPath` in some form.
=> Improved BaseRouteHandler#getModelClassFromPath

blueprints/ember-cli-mirage/index.js, package.json
Fixes this deprecation warning
```
warning ember-cli-mirage > exists-sync@0.0.3: Please replace with usage of fs.existsSync
```
=> Fix exists-sync deprecation by replacing with fs.existsSync

blueprints/ember-cli-mirage/index.js
This warning was introduced for applications generated with ember-cli <= 1.13.8. It's safe to assume that none of the applications which weren't updated yet will install ember-cli-mirage now if they haven't so far.
On the other hand this warning is misleading for all new generated projects with ember-cli >= 3.0.0.
Fixes #1300
=> fix: remove outdated warning about missing destroy-app helper

addon-test-support/setup-mirage.js
In one of our test cases, the `afterEach` cases is called, when there is no server defined, which results in an error and in the case of mocha this cause the whole test suite to fail. Although this is most probably a problem there, I think that it is worth having this simple check here as well.
=> Check if there is a server before shutting it down

addon/route-handlers/base.js, tests/integration/server/shorthands/patch-shorthand-with-relationships-test.js
The default behaviour of the JSON:API serializer is to dasherize the relationship names, so having a multiple word relationship name, will result in a block like `... "post-author": { data: null }...`.
Without this patch the `_getAttrsForRequest` fails, because it cannot find the correct association (_Cannot read isPolymorphic of undefined_)
=> Camelize the relationship name before getting the association

addon/route-handlers/base.js, tests/integration/route-handlers/assertions-test.js
Hey! This repo is awesome. I have honestly never seen a test 'sweet' as expansive as this one.
I came across an issue in my code where I had not explicitly defined an association that I was posting via the relationships attr. (json:api) 
This resulted in a javascript exception on [this line](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/base.js#L66): around not being able to access the property `isPolymorphic of undefined`. 
This PR adds a simple assert in that code to help people fix this problem if they hit it. 
* Adds assert that ensures associations are defined when being included in json:api post requests
I tried to match the language style from other asserts.
=> Adds assert for association definition

blueprints/ember-cli-mirage/files/__root__/config.js
Link to shorthands documentation was still pointing to older version v0.3.x.
=> Updated link to shorthands documentation

index.js, package.json, yarn.lock
This change does not, like originally intended, make Pretender a peer
dependency. There's a lot of work and debate being done here, so in the
mean time let's unlock `fetch` support in Mirage.
Dependency changes
------------------
* pretender 1.6 => 2.1. I've locked at 2.1.0 until
pretenderjs/pretender#235 is resolved. This will require code changes
on our end, and thus I don't want this sliding from underneath us and
causing unnecessary weeping and gnashing of teeth.
* Add xg-wang/whatwg-fetch. Required for the upgrade.
* fake-xml-http-request 1.4.0 => 2.0.0. Required for the upgrade.
* route-recognizer 0.2.3 => 0.3.4. Required for the upgrade.
* ember-cli-node-assets 0.1.4 => 0.2.2. Because why not! I'm kneed deep
in this stuff, so I may as well keep this up to date.
=> Support Pretender 2

.npmignore, blueprints/.jshintrc
Let's trim some fat.
Below results are from `npm publish --dry-run`:
Before
------
```
npm notice === Tarball Details ===
npm notice name:          ember-cli-mirage
npm notice version:       0.4.9
npm notice package size:  255.3 kB
npm notice unpacked size: 865.4 kB
npm notice shasum:        e359b3345fa75c80a876f4ed20ddfa8a19ad1106
npm notice integrity:     sha512-l7uJ/QaW6Vwun[...]4b7gMwpKArLWw==
npm notice total files:   74<Paste>
```
```
npm notice === Tarball Details ===
npm notice name:          ember-cli-mirage
npm notice version:       0.4.9
npm notice package size:  44.0 kB
npm notice unpacked size: 183.7 kB
npm notice shasum:        d42e6082d728fc2d8cbafa7600c863849eb4857c
npm notice integrity:     sha512-GgGNVMXXg9ZWq[...]Ei50rC/B9Qp2Q==
npm notice total files:   69
```
=> Expand npmignore

addon/orm/associations/association.js, addon/orm/associations/belongs-to.js, addon/orm/associations/has-many.js, addon/orm/model.js, addon/route-handlers/base.js, addon/server.js
Similarly to #1092 and #1168, https://github.com/samselikoff/ember-cli-mirage/blob/99c927009a539f7e1fbfb8f6e857372e2319856b/addon/orm/associations/association.js#L52-L54 and https://github.com/samselikoff/ember-cli-mirage/blob/99c927009a539f7e1fbfb8f6e857372e2319856b/addon/orm/associations/association.js#L56-L58 fail in production builds due to minification.
This PR replaces usages of `isHasMany` and `isBelongsTo` with `instanceof` and uses overrides within the associations classes themselves (for `identifier`).
=> Use instanceof and overrides to distinguish associations

tests/dummy/app/pods/docs/advanced/identity-managers/template.md, tests/dummy/app/pods/docs/template.hbs, tests/dummy/app/router.js
Documentation was missing since implementation done in #977.
=> add docs for identity managers

addon/route-handler.js, tests/integration/server/falsy-responses-test.js
Simplifies checking for blank response to merely change to 200 when
the response type would have been a 204 and the response is not
undefined or an empty string. This also matches the heuristic in the
204-non-empty-payload warning.
=> Improve automatic response type setting

addon/route-handler.js
I had a handler that looked something like this, and was baffled for a while this afternoon as to why the callback was never triggering even though I saw Mirage logging that it had handled the request:
```js
this.post('/some-path', async () => {
// some promise-y stuff
});
```
It turns out, on platforms where `async` functions are supported natively, `Ember.typeOf` incorrectly [identifies them as objects](https://github.com/emberjs/ember.js/issues/15151). Ultimately it was decided [not to extend `Ember.typeOf` to handle this](https://github.com/emberjs/ember.js/pull/15165) in favor of native `typeof` instead.
=> Allow native async functions as route handlers

tests/dummy/app/index.html
Now that the dummy app is being used as the actual website (!!!) I think it deserves a proper title.
=> Set the dummy app's <title> to 'EmberCLI Mirage'

tests/dummy/app/pods/docs/getting-started/quickstart/template.md
There is also an issue with:
See the `serializer guide` to learn more.
Not sure where it should point to
=> fix: shorthand link

addon/response.js, tests/integration/server/custom-responses-test.js, tests/unit/response-test.js
As a 204 response has no response body, a Content-Type is basically meaningless. It doesn't seem to be a violation of any spec to have one AFAICT, but as it is optional and does not make sense here, it seems better to not add it automatically.
=> Omit default Content-Type header for 204 responses

addon/serializers/active-model-serializer.js, tests/unit/serializers/active-model-serializer-test.js
BREAKING CHANGE: This applies to the ActiveModelSerializer and
RestSerializer.
The `normalize` property on serializers helps Mirage's shorthands work
by transforming differently formatted payloads into JSON:API documents.
These documents are then used by Mirage to update the database accordingly.
There was a gap in the default `normalize` method for a long time, in that
it didn't take REST payloads that included foreign keys and looked like
```js
let payload = {
contact: {
id: 1,
name: 'Link',
address: 1
}
};
```
and turn that `address` key into a proper JSON:API relationship:
```js
data: {
type: 'contacts',
id: 1,
attributes: {
name: 'Link'
},
relationships: {
address: {
data: {
type: 'address',
id: 1
}
}
}
}
```
We added this feature a while ago, and it's controlled with the …
=> feat: `normalizeIds` serializer property defaults to true

addon/route-handlers/function.js, addon/server.js, package.json, tests/helpers/reg-exp-from-string.js, tests/integration/route-handlers/function-handler/normalize-request-attrs-test.js, tests/integration/server/create-and-create-list-test.js
BREAKING CHANGE: There are several places in Mirage's APIs that were
intended to be used with singularized versions of model names, but just
so happened to work if a non-singularized version was passed in.
This behavior was discovered during a refactor, and the non-singularized
versions were maintained to avoid breaking apps. Now that we're moving to
1.0, we're removing this deprecated/unintentional behavior.
- `server.create` and `server.createList` were coded to take a singularized
model name, e.g. `server.create('user')`. It just so happens that
`server.create('users')` also works. That pluralized version is now removed
from Mirage.
If you're running the latest 0.x version you should see a deprecation
message letting you know where to change it. Otherwise, it should be
a pretty …
=> drop deprecated forms of create, createList and normalizedRequestAttrs

tests/dummy/app/pods/docs/advanced/route-handlers/template.md
The current link leads to a "Not found" page. This PR changes the target to what I'm guessing is the intended location.
=> Fix internal link to Schema docs

addon/serializer.js, addon/serializers/json-api-serializer.js
This PR cuts more than half a megabyte from any app that uses mirage.
The problem is that:
```js
import _ from 'lodash';
let item = _(value);
```
needs to put methods on `item` for every possible thing lodash supports. Most of which aren't needed.
This isn't one of the cases where a more aggressive module bundler could try to optimize them out. This style really just can't be statically optimized. It's a pity, because the chaining style is easier to read IMO.
=> Save over 500KB with one weird trick

index.js, package.json, yarn.lock
These are dependencies of pretender. They stopped being necessary when mirage switched to loading pretender via ember-auto-import. When consumed that way, pretender already does the right thing and includes its own dependencies automatically.
Prior to this PR, all of these were being included twice.
=> Remove duplicated dependencies

addon/assert.js, addon/route-handler.js, addon/server.js, tests/integration/route-handlers/function-handler/basic-test.js, tests/integration/route-handlers/function-handler/normalize-request-attrs-test.js, tests/integration/route-handlers/function-handler/serialize-test.js
Many promises were being swallowed because I think I originally wrote this code when I didn't understand promises.
I always had the extra `console.log` lines because I couldn't figure out how to get the error messages to consistently show up. Now that all promises in the request-response cycle are always being either resolved or rejected, we can rely on upstream tooling to properly display error messages (both in dev and in testing).
The `console.log` noise was also problematic when testing errors or in some of our recent work getting Mirage to run in express.
If anybody starts using these changes and feel it obfuscates Mirage's error messaging too much please let me know. I'm still not 100% satisfied with the state of error handling in many code paths in modern Ember app development and …
=> Better logging

addon/serializers/json-api-serializer.js, tests/integration/serializers/json-api-serializer/associations/collection-test.js, tests/integration/serializers/json-api-serializer/associations/model-test.js
- allows for per-relationship inclusion of linkage data
- use this when alwaysIncludeLinkageData is not granular enough
Example:
```js
export default JSONAPISerializer.extend({
shouldIncludeLinkageData(relationshipKey, model) {
if (relationshipKey === 'author' || relationshipKey === 'ghostWriter') {
return true;
}
return false;
}
})
```
@mattmcmanus & @lukemelia
=> Adds overridable shouldIncludeLinkageData method to JsonApiSerializer

addon/assert.js, addon/serializers/json-api-serializer.js
- Make it an ES6 class and share `extends` from base `Serializer` class
=> Document and cleanup JSONAPISerializer

blueprints/ember-cli-mirage/index.js
There isn't any need for a global `server` variable in new testing API. Allowing it in ESLint and JSHint configuration isn't necessary for new apps anymore.
=> do not whitelist global server in blueprint

addon-test-support/index.js, test-projects/01-basic-app/tests/acceptance/faker-test.js, test-projects/01-basic-app/tests/acceptance/start-mirage-test.js, tests/dummy/app/pods/docs/writing-your-server/acceptance-testing/template.md
Before:
```js
import setupMirage from 'ember-cli-mirage/test-support/setup-mirage';
```
After:
```js
import { setupMirage } from 'ember-cli-mirage/test-support';
```
It's less verbose. I also think it's more inline with rest of the ecosystem. Have a look at [Ember Power Select](https://ember-power-select.com/docs/test-helpers), [Ember Simple Auth](https://github.com/simplabs/ember-simple-auth#testing) and [Ember Lifeline](https://ember-lifeline.github.io/ember-lifeline/docs/testing) for example.
=> export setupMirage from test-support directly

addon/orm/schema.js
It seems that the documentation for the `findOrCreateBy` method on the schema was referencing `findBy` instead. This updates it so it's using the correct method.
=> Fix where the  docs reference wrong method

addon/orm/model.js, tests/integration/orm/mixed/regressions/1613-two-bidirectional-many-to-many-with-same-target-model-update-bug-test.js, tests/integration/server/regressions/1613-two-bidirectional-many-to-many-with-same-target-model-update-bug-test.js, tests/integration/server/regressions/same-model-different-attribute-inverses-bug-test.js
Hey, I’m running into an obscure seemingly-bug in [this open-source application](https://github.com/backspace/prison-rideshare-ui) I maintain. This test demonstrates the problem in a more focused way, but here’s the context from the production application in case it’s helpful:
The relevant portion of the data model is that there are (car) `ride`s that can be assigned to `driver`s and `carOwner`s, which are both of type `person`. Here’s the awkward nomenclature:
```
ride:
driver: belongsTo('person', { inverse: 'drivings' }),
carOwner: belongsTo('person', { inverse: 'carOwnings' }),
person:
drivings: hasMany('ride', { inverse: 'driver' }),
carOwnings: hasMany('ride', { inverse: 'carOwner' }),
```
I ran into this because in the tests, I have a `PATCH` to update a `ride` by assigning a …
=> A model with two hasMany relationships to the same type doesn’t properly store both attributes

tests/dummy/app/pods/docs/data-layer/factories/template.md
Everything after/below this link is missing on the live page. This should fix the issue.
=> Fix bug - Old testing link on Factories breaks documentation below

tests/dummy/app/pods/docs/testing/acceptance-tests/template.md
The example here is missing the opening curly bracket.
=> Bug fix for testing documentation

tests/dummy/app/pods/docs/testing/acceptance-tests/template.md
Hi!
The Fixtures section suggests naming the fixtures file as `countries.js`.
Then, the Acceptance Testing section suggests loading it as `server.loadFixtures('country')`.
Since both Ember Data and Mirage are notorious for using different pluralization in different places, this particular mismatch didn't raise suspicion.
The problem is, though, it should be `server.loadFixtures('countries')` to load `countries.js`.
And the worst thing is that using a non-existing fixture file name fails silently.
This set me back for a while and took quite some time to figure out.
Hope this tiny change in documentation will help other users.
PS Tell me if you want me to create an issue requiring for `loadFixtures('non-existing')` to throw a meaningful error. I strongly believe it should be.
=> Docs: Use consistent name of the fixtures file

tests/dummy/app/pods/docs/data-layer/database/template.md
Thanks to your pointers, this closes #1709.
=> Fix database API documentation links

package.json
The 01-basic-app test project had a failing fastboot test under our
Travis floating-deps test case. This means the fastboot tests passed
when all node_modules were installed using our `yarn.lock` file, but
failed when `yarn install --no-lockfile` was used. This means
there was some bump in a transitive dependency that caused an issue
in one of the fastboot tests in 01-basic-app, when newing up a Fastboot
instance.
To track down the problematic dependency, we cut the yarn.lockfile in
half and deleted it, regenerating the remaining entries until we found
the problematic one. It turned out to be terser-webpack-plugin, which
is in our dependency graph because of Ember Auto Import. By pinning
the dependency, all tests now pass when `yarn install --no-lockfile`
is used.
=> Fix fastboot test failure under floating deps

tests/dummy/app/pods/docs/data-layer/factories/template.md
I assume you meant to write `server.create('user')` unless there is actually a shorthand version.
=> Fix a mistake in Factories docs

tests/dummy/app/pods/docs/route-handlers/functions/template.md
Based on this issue and pull request fix [here](https://github.com/samselikoff/ember-cli-mirage/issues/1634). The function's documentation should be updated to reflect the use of `function` over `arrow function`.
=> Fix functions template

tests/dummy/app/pods/docs/advanced/switching-between-scenarios/template.md, tests/dummy/app/pods/docs/template.hbs, tests/dummy/app/router.js
This PR adds some documentation about scenarios and ways to use them more effectively.
=> Add documention clarifying use of scenarios (#1427)

addon/server.js, index.js, package.json, vendor/add-qunit-option.js
Resolves #1783 
Unfortunately, I had to add `after: ember-qunit` to the `package.json` to ensure that `window.QUnit` is actually defined already by the time that we try to register the QUnit option. Registering it later when the server is created is unfortunately not possible, since the options have to be defined already by the time that QUnit is running the tests.
/cc @samselikoff
=> Add "Mirage logging" checkbox to QUnit user interface

tests/dummy/app/pods/docs/advanced/customizing-the-inflector/template.md
=> Update Customizing the inflector docs

package.json, yarn.lock
Resolves the following errors on the floating dependencies tests (e.g. https://travis-ci.org/github/miragejs/ember-cli-mirage/jobs/692761519):
```
Merge error: conflicting capitalizations:
vendor/moment/locale/en-SG.js in /home/travis/build/miragejs/ember-cli-mirage/tmp/broccoli_merge_trees-input_base_path-COwZk18H.tmp/1
vendor/moment/locale/en-sg.js in /home/travis/build/miragejs/ember-cli-mirage/tmp/broccoli_merge_trees-input_base_path-COwZk18H.tmp/1
Remove one of the files and re-add it with matching capitalization.
```
See https://github.com/jasonmit/ember-cli-moment-shim/issues/183
=> Fix moment

addon/start-mirage.js
`getWithDefault` is deprecated by https://github.com/emberjs/rfcs/pull/554, causing failures with Ember Canary. See #1970
=> Replace getWithDefault (Fixes #1970)

yarn.lock
So `yarn install` doesn't produce a diff
=> Fix discrepancy in lockfile

ember-cli-build.js
We have ember-cli-fastboot installed so it can be made available to some
of the test projects, but we never use it to actually serve the dummy
app (which is the docs app).
Thus, if a new user clones + runs the repo, unless they have the
FASTBOOT_DISABLED ENV var set, `ember s` will try to serve the
dummy app via FastBoot which will cause errors.
With the addon blacklisted, ember-cli-fastboot will just never be able
to affect the dummy app at all.
=> Add Fastboot to addon blacklist for dummy app

app/initializers/ember-cli-mirage.js
The ES module spec doesn't support "optional" exports. If you try to import a name from a module and that name is not exported, it's a SyntaxError.
Mirage tries to import `default`, `testConfig`, and `makeServer` from the user's config, but they are treated as optional.
The solution is to import the module's whole namespace (`import * as...`) and then inspect the namespace object.
=> Fix invalid use of ES modules

addon-test-support/index.js, index.js, package.json, tests/acceptance/home-test.js, tests/index.html, vendor/add-qunit-option.js, yarn.lock
Fixes https://github.com/miragejs/ember-cli-mirage/issues/2091
There were no tests for the original adding of the option, I dont see how to add tests as it not a test of the addon but how the addon works with Qunit.
- Moved the adding of the option from vendor/add-qunit-option to test-support/qunit-configuration same as qunit5 does
- Moved import of code from index.js to test-support/index.js.  This means if you never import setupMirage you will never see the option added, which kinda makes sense. This also means you wont see it if you run the tests in this repo, since none of the tests import setupMirage
=> Update mirage logging option to work with qunit5

package.json, yarn.lock
This addon works fine with 0.2.x and requiring 0.3.0 can cause dependency version conflicts, so let's widen the requirement so that users can choose a version that does not cause them any conflicts.
/cc @samselikoff
=> Widen `ember-get-config` dependency requirement

package.json, yarn.lock
ember-data updated its dependency from ember-inflector to 4.0.1.
Allow ember-cli-mirage to depend on ember-inflector@4 to avoid dependency
lint error.
=> Allow ember-inflector@^4.0.0

tests/dummy/app/pods/docs/data-layer/serializers/index/template.md
=> Fix typo in docs

tests/dummy/app/pods/docs/advanced/server-configuration/template.md
Came across some small typos on the docs :-)
=> Correct some typos

ember-cli-build.js
This PR configures the add-on [`ember-composable-helpers`](https://github.com/DockYard/ember-composable-helpers) to only include a specific set of helpers when the project is built.
According to your HBS files, you only use the helper `sort-by`:
https://github.com/miragejs/ember-cli-mirage/search?l=handlebars
=> build: only include used composable-helpers

tests/dummy/app/pods/docs/data-layer/factories/template.md
The code snippet changed in this PR is described with the following text `Here we define a withComments trait that creates 3 comments for a newly created post:`
Creating a post requires having a factory on the path `mirage/factories/post.js` as opposed to `mirage/factories/user.js`
Also to keep it consistent with the rest of the examples where posts have a property called `title`, as opposed to `name`, I went ahead and updated the `name` property on the factory to be `title`.
=> docs: factory - fix traits example

addon/deprecate-imports.js, addon/index.js
@cah-briangantzler this is the dirty but seem to be working solution for re-exports deprecation.
=> Deprecate miragejs re-exports

addon/ember-data.js, blueprints/ember-cli-mirage/files/__root__/serializers/application.js, blueprints/mirage-factory/files/__root__/factories/__name__.js, blueprints/mirage-model/files/__root__/models/__name__.js, test-projects/01-basic-app/mirage/factories/nested/thing.js, test-projects/01-basic-app/mirage/factories/user.js, test-projects/01-basic-app/mirage/models/nested/thing.js, test-projects/01-basic-app/mirage/serializers/application.js, test-projects/01-basic-app/package.json, tests/dummy/app/pods/docs/data-layer/factories/template.md, tests/dummy/app/pods/docs/data-layer/models/template.md, tests/dummy/app/pods/docs/data-layer/orm/template.md, tests/dummy/app/pods/docs/data-layer/serializers/index/template.md, tests/dummy/app/pods/docs/getting-started/overview/template.md, tests/dummy/app/pods/docs/getting-started/upgrade-guide/template.md, tests/dummy/app/pods/docs/route-handlers/functions/template.md, tests/dummy/app/pods/docs/testing/acceptance-tests/template.md, tests/dummy/mirage/serializers/application.js, tests/unit/serializers/ember-data-serializer-discover-test.js
Internally for tests and such ember-cli-mirage still imported all the miragejs objects  from the re-exported ones in ember-cli-mirage instead of miragejs proper.
Updated them.
=> updated all imports for miragejs objects to be from miragejs

config/ember-try.js
This does not fix CI but fixes following error:
```
To use these addons, your app needs ember-auto-import >= 2: ember-source
```
We'll need to update some other dependencies to make CI pass, but let's keep PRs focused and fixing one error at a time.
=> Add ember-auto-import and webpack to Ember v4 scenarios

config/ember-try.js, package.json, tests/dummy/config/optional-features.json, yarn.lock
This removes deprecations and build failure caused by `ember.edition`  field in `package.json` and missing optional features
=> Enable Ember Octane features to fix Ember v4 scenarios

package.json, yarn.lock
We can't go beyond 0.41.0 as Node 10 support was dropped in v0.42.0
=> Bump @embroider/macros from 0.40.0 to 0.41.0

package.json, tests/helpers/reg-exp-from-string.js
couldn't find any usage, seem not used anymore hence can be safely deleted
=> Remove unused helper reg-exp-from-string and escape-string-regexp devDependency

.github/workflows/ci.yml, config/ember-try.js
This addon doesn't do anything fancy that requires recent-ish versions of Ember.js or Ember CLI so testing agains older versions may give us more confidence and wider support.
=> Add 3.12 LTS scenario to test matrix

addon/get-rfc232-test-context.js, addon/utils/ember-data.js, package.json, yarn.lock
`require` a pre-ES-module feature that continues to work in Ember but is fragile and unreliable under ES-module-first build tooling like Embroider.
This PR replaces two uses with embroider macros instead, which are designed to allow dynamism without sacrificing static analysis.
=> remove some usage of runtime require

package.json, yarn.lock
This is breaking change and will require major version bump.
Per [ember-auto-import 1.x to 2.x migration guide](https://github.com/ef4/ember-auto-import/blob/main/docs/upgrade-guide-2.0.md):
> addons that upgrade to ember-auto-import >= 2 will only work in apps that have ember-auto-import >= 2, so they should do their own semver major releases when they upgrade
There is a bunch of wins (especially performance) for apps that update to e-a-i v2 and e-a-i v2 will be a hard requirement for apps to run Ember v4 (which should not be big deal as apps running v2 should be able to use addons running e-a-i v1, but why not).
There is great write up from @buschtoens about this https://twitter.com/buschtoens/status/1449745386571247620
=> Bump ember-auto-import from 1.12.0 to 2.2.4

addon/utils/inflector.js
The [@ember/string](https://api.emberjs.com/ember/release/classes/String) library doesn't provide these methods, they are to be
found in [ember-inflector](https://github.com/emberjs/ember-inflector).
=> Point users of deprecated inflector methods to ember-inflector

.eslintrc.js, package.json, test-support.d.ts, types-tests/test-support.test.ts, types-tests/tsconfig.json, yarn.lock
This PR ensures that `import { setupMirage } from 'ember-cli-mirage/test-support';` works as expected for TypeScript users. It also adds a small `types-tests` suite to verify that they work as expected.
@SergeAstapov if I were to open a second copy of this PR against the `v2` branch, is there a chance you'd be willing to include it in a 2.x release as well, since 3.0 is still in alpha? 🙂
=> Add TS declaration for `setupMirage`

.eslintrc.js, package.json, test-support.d.ts, types-tests/test-support.test.ts, types-tests/tsconfig.json, yarn.lock
This backports #2366 to the `v2` branch. If possible I'd love to see it land here as well, since 3.0 is still in alpha 🙂
=> [v2] Add TS declaration for `setupMirage`

addon-test-support/setup-mirage.js, tests/dummy/app/pods/docs/template.hbs, tests/dummy/app/pods/docs/testing/setup-mirage/template.md
Fixes: https://github.com/miragejs/ember-cli-mirage/issues/2370
`startMirage` takes an options parameter to aid in creating the server. Allowed `setupMirage` to also take an options param and pass to `startMirage`. 
@dfreeman Not good with TS. Could you make a followup PR after this is merged to update the `test-support.d.ts` if thats where the types should go. Since these options are passed to `startMirage`, it should also have a type def, there are times when it can be called directly, which may mean the default export from `mirage/config.js` may also need a type.
=> Allow for setupMirage to pass options to startMirage

addon/ember-data.js, addon/utils/ember-data.js, app/initializers/ember-cli-mirage.js
By discovering the ED models via the `modelFor` method on the `store`, rather than statically `require`'ing them (@runspired lead me down this path as a resolution).
Resolves: https://github.com/miragejs/ember-cli-mirage/issues/2441
I've confirmed that the deprecation no longer appears for our app when running tests:
1. via `localhost:4200/tests`
2. via `yarn run test`
_For the record I don't think this PR should be merged in its current state - its more a POC to demonstrate there is a way to resolve this issue. Theres probably a much nicer way to get a handle on an application instance that doesn't involve a global on `window`_
=> Resolve the deprecate-early-static warning from ember-data

packages/ember-cli-mirage/package.json, pnpm-lock.yaml
=> remove ember-destroyable-polyfill dependency

packages/ember-cli-mirage/addon/utils/ember-data.js, packages/ember-cli-mirage/package.json, pnpm-lock.yaml
While ember-data is usually installed it's also possible to use
@ember-data/model (and other packages directly). Since ember-data
provides @ember-data/model I don't think we need to detect both.
I'm not sure why this resolves to false in an app with either `ember-data` or `@ember-data/model` installed. I would expect true in both of those cases. I'm hoping @runspired or @ef4 might be able to shine some light on why this package may not work with the check in `dependencySatisfies`? I feel like maybe I'm missing something obvious, but I can't see it.
=> Detect @ember-data/model instead of ember-data meta-package

packages/ember-cli-mirage-docs/app/templates/docs/advanced/server-configuration.md
Exporting a named function is deprecated and this now matches the docs
directly above.
=> Export default in server docs

packages/ember-cli-mirage-docs/app/templates/docs/testing/integration-and-unit-tests.md
I think we should use native setter syntax in documentation examples. Is there a reason we should use .set? Backwards compatibility?
=> Use native setters in documentation examples

packages/ember-cli-mirage-docs/app/templates/docs/advanced/environment-options.md, packages/ember-cli-mirage-docs/app/templates/docs/data-layer/database.md, packages/ember-cli-mirage-docs/app/templates/docs/data-layer/factories.md, packages/ember-cli-mirage-docs/app/templates/docs/data-layer/models.md, packages/ember-cli-mirage-docs/app/templates/docs/data-layer/relationships.md, packages/ember-cli-mirage-docs/app/templates/docs/data-layer/serializers/ember-data-serializer.md, packages/ember-cli-mirage-docs/app/templates/docs/data-layer/serializers/index.md, packages/ember-cli-mirage-docs/app/templates/docs/getting-started/installation.md, packages/ember-cli-mirage-docs/app/templates/docs/getting-started/upgrade-guide.md, packages/ember-cli-mirage-docs/app/templates/docs/testing/assertions.md
=> Update v3 upgrade guide

packages/ember-cli-mirage/config/environment.js
As mentioned in https://github.com/miragejs/ember-cli-mirage/issues/2558#issuecomment-1767991362, on Windows, my team member @Ajanth wasn't able to run the desired server even after I updated `ember-cli-mirage` to `v3.0.1` (see #2559).
We think the issue is related to [`config/environment.js#L14`](https://github.com/miragejs/ember-cli-mirage/blob/v3.0.1/packages/ember-cli-mirage/config/environment.js#L14), due to `process.env.PWD` and the hardcoded `/`'s.
After replacing `process.env.PWD` with `process.cwd()` and `/` with `path.join()`, we checked that we can run the server on both Windows and Mac. On Mac, I saw the same value logged for (1), (2), and (3):
```js
console.log('(1) ' + `${process.env.PWD}/server/proxies`);
console.log('(2) ' + path.join(process.env.PWD, 'server', …
```
=> Fix usingProxy() on Windows

.npmrc, package.json
Volta isn't needed any more since you're using pnpm and it has its own way to pick the node version https://pnpm.io/npmrc#use-node-version
=> use pnpm node version selection instead of volta

packages/ember-cli-mirage/package.json, pnpm-lock.yaml
This adds `^v5.0.0` to the list of allowed versions for ember-inflector. The major is not breaking, it's just been converted to a v2 addon
=> add v5.x to the list of ember-inflector versions
